/*
 * Copyright (c) 2022 Winsider Seminars & Solutions, Inc.  All rights reserved.
 *
 * This file is part of System Informer.
 *
 * Authors:
 *
 *     jxy-s   2026
 *
 */

#ifndef _ONLINECHECKSINTF_H
#define _ONLINECHECKSINTF_H

#define ONLINECHECKS_PLUGIN_NAME L"OnlineChecks"
#define ONLINECHECKS_INTERFACE_VERSION 2

typedef enum _ONLINECHECKS_LOOKUP_RESULT
{
    OnlineChecksLookupFound,
    OnlineChecksLookupNotFound,
    OnlineChecksLookupUnavailable,
} ONLINECHECKS_LOOKUP_RESULT, *PONLINECHECKS_LOOKUP_RESULT;

typedef struct _ONLINECHECKS_VIRUSTOTAL_RESULT
{
    ULONG HttpStatus;
    LARGE_INTEGER Expiry;
    ULONG64 Malicious;
    ULONG64 Undetected;
} ONLINECHECKS_VIRUSTOTAL_RESULT, *PONLINECHECKS_VIRUSTOTAL_RESULT;

typedef struct _ONLINECHECKS_HYBRIDANALYSIS_RESULT
{
    ULONG HttpStatus;
    LARGE_INTEGER Expiry;
    ULONG64 MultiscanResult;
    PPH_STRING VxFamily;
} ONLINECHECKS_HYBRIDANALYSIS_RESULT, *PONLINECHECKS_HYBRIDANALYSIS_RESULT;

typedef ONLINECHECKS_LOOKUP_RESULT (NTAPI* PONLINECHECKS_QUERY_VIRUSTOTAL)(
    _In_ PPH_STRING Sha256,
    _Out_ PONLINECHECKS_VIRUSTOTAL_RESULT Result
    );

typedef ONLINECHECKS_LOOKUP_RESULT (NTAPI* PONLINECHECKS_QUERY_HYBRIDANALYSIS)(
    _In_ PPH_STRING Sha256,
    _Out_ PONLINECHECKS_HYBRIDANALYSIS_RESULT Result
    );

typedef struct _ONLINECHECKS_VIRUSTOTAL_REPORT
{
    ULONG HttpStatus;
    ULONG64 Malicious;
    ULONG64 Undetected;
    PPH_STRING ScanDate;
} ONLINECHECKS_VIRUSTOTAL_REPORT, *PONLINECHECKS_VIRUSTOTAL_REPORT;

typedef struct _ONLINECHECKS_HYBRIDANALYSIS_REPORT
{
    ULONG HttpStatus;
    ULONG64 ThreatScore;
    ULONG64 MultiscanResult;
    PPH_STRING Verdict;
    PPH_STRING VxFamily;
} ONLINECHECKS_HYBRIDANALYSIS_REPORT, *PONLINECHECKS_HYBRIDANALYSIS_REPORT;

typedef NTSTATUS (NTAPI* PONLINECHECKS_LOOKUP_VIRUSTOTAL)(
    _In_ PPH_STRING Sha256,
    _Out_ PONLINECHECKS_VIRUSTOTAL_REPORT Report
    );

typedef NTSTATUS (NTAPI* PONLINECHECKS_LOOKUP_HYBRIDANALYSIS)(
    _In_ PPH_STRING Sha256,
    _Out_ PONLINECHECKS_HYBRIDANALYSIS_REPORT Report
    );

typedef struct _ONLINECHECKS_INTERFACE
{
    ULONG Version;
    PONLINECHECKS_QUERY_VIRUSTOTAL QueryCachedVirusTotal;
    PONLINECHECKS_QUERY_HYBRIDANALYSIS QueryCachedHybridAnalysis;
    PONLINECHECKS_LOOKUP_VIRUSTOTAL LookupVirusTotal;
    PONLINECHECKS_LOOKUP_HYBRIDANALYSIS LookupHybridAnalysis;
} ONLINECHECKS_INTERFACE, *PONLINECHECKS_INTERFACE;

#endif
