//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ExtendedTools.rc
//
#define ID_PROCESS_UNLOADEDMODULES      101
#define IDD_UNLOADEDDLLS                101
#define IDD_OBJALPCPORT                 102
#define ID_THREAD_CANCELIO              102
#define IDD_OBJTPWORKERFACTORY          103
#define ID_MODULE_SERVICES              103
#define IDD_MODSERVICES                 104
#define ID_VIEW_MEMORYLISTS             104
#define IDD_MEMLISTS                    105
#define IDC_DISK                        105
#define IDD_DIALOG1                     106
#define IDD_PROCDISKNET                 106
#define IDC_NETWORK                     106
#define ID_VIEW_DISKANDNETWORK          107
#define IDD_SYSDISKNET_PANEL            108
#define ID_PROCESS_WSWATCH              108
#define IDD_SYSINFO_DISKPANEL           108
#define IDD_OPTIONS                     109
#define IDC_GPU                         109
#define IDD_WSWATCH                     110
#define IDC_DEDICATED                   110
#define IDR_EMPTYMEMLISTS               111
#define IDD_SYSGPUINFO                  111
#define IDC_SHARED                      111
#define IDD_SYSINFO_GPU                 111
#define IDR_MENU1                       112
#define IDR_DISK                        112
#define IDD_SYSGPUINFO_PANEL            112
#define ID_VIEW_GPUINFORMATION          112
#define IDD_SYSINFO_GPUPANEL            112
#define IDD_PROCGPU                     113
#define IDD_SYSINFO_DISK                114
#define IDD_GPUNODES                    115
#define IDD_SYSINFO_NETPANEL            116
#define IDD_SYSINFO_NET                 117
#define IDC_LIST                        1001
#define IDC_REFRESH                     1002
#define IDC_SEQUENCENUMBER              1003
#define IDC_PORTCONTEXT                 1004
#define IDC_WORKERTHREADSTART           1005
#define IDC_WORKERTHREADCONTEXT         1006
#define IDC_SERVICES_LAYOUT             1006
#define IDC_MESSAGE                     1007
#define IDC_ZZEROED_V                   1009
#define IDC_ZFREE_V                     1010
#define IDC_ZMODIFIED_V                 1011
#define IDC_ZMODIFIEDNOWRITE_V          1012
#define IDC_ZBAD_V                      1013
#define IDC_ZSTANDBY_V                  1014
#define IDC_ZSTANDBY0_V                 1015
#define IDC_ZSTANDBY1_V                 1016
#define IDC_ZSTANDBY2_V                 1017
#define IDC_ZSTANDBY3_V                 1018
#define IDC_ZSTANDBY4_V                 1019
#define IDC_ZSTANDBY5_V                 1020
#define IDC_ZSTANDBY6_V                 1021
#define IDC_ZSTANDBY7_V                 1022
#define IDC_ZREADS_V                    1023
#define IDC_ZREADBYTES_V                1024
#define IDC_ZREADBYTESDELTA_V           1025
#define IDC_ZWRITES_V                   1026
#define IDC_ZWRITEBYTES_V               1027
#define IDC_ZWRITEBYTESDELTA_V          1028
#define IDC_ZRECEIVES_V                 1029
#define IDC_ZRECEIVEBYTES_V             1030
#define IDC_ZRECEIVEBYTESDELTA_V        1031
#define IDC_ZSENDS_V                    1032
#define IDC_ZSENDBYTES_V                1033
#define IDC_ZSENDBYTESDELTA_V           1034
#define IDC_ENABLEETW                   1038
#define IDC_ENABLEETWMONITOR            1038
#define IDC_ENABLE                      1039
#define IDC_WSWATCHENABLED              1041
#define IDC_ZREPURPOSED_V               1042
#define IDC_ZREPURPOSED0_V              1043
#define IDC_ZREPURPOSED1_V              1044
#define IDC_ZREPURPOSED2_V              1045
#define IDC_ZREPURPOSED3_V              1046
#define IDC_ZREPURPOSED4_V              1047
#define IDC_ZREPURPOSED5_V              1048
#define IDC_ZREPURPOSED6_V              1049
#define IDC_ZREPURPOSED7_V              1050
#define IDC_BUTTON1                     1051
#define IDC_EMPTY                       1051
#define IDC_NODES                       1051
#define IDC_CHECK1                      1052
#define IDC_ENABLEGPUMONITOR            1052
#define IDC_EXAMPLE                     1052
#define IDC_GROUPGPU                    1053
#define IDC_GROUPDEDICATED              1054
#define IDC_GROUPSHARED                 1055
#define IDC_ZDEDICATEDCURRENT_V         1055
#define IDC_ZDEDICATEDLIMIT_V           1056
#define IDC_ZSHAREDCURRENT_V            1057
#define IDC_ZSHAREDLIMIT_V              1058
#define IDC_ZDEDICATEDCOMMITTED_V       1059
#define IDC_ZSHAREDCOMMITTED_V          1060
#define IDC_ZRUNNINGTIME_V              1063
#define IDC_ZCONTEXTSWITCHES_V          1064
#define IDC_ZTOTALALLOCATED_V           1065
#define IDC_ZTOTALRESERVED_V            1066
#define IDC_ZWRITECOMBINEDALLOCATED_V   1067
#define IDC_ZWRITECOMBINEDRESERVED_V    1068
#define IDC_ZCACHEDALLOCATED_V          1069
#define IDC_ZCACHEDRESERVED_V           1070
#define IDC_ZSECTIONALLOCATED_V         1071
#define IDC_ZSECTIONRESERVED_V          1072
#define IDC_ZTOTALSEGMENTS_V            1073
#define IDC_ZTOTALNODES_V               1074
#define IDC_TITLE                       1075
#define IDC_GRAPH_LAYOUT                1076
#define IDC_LAYOUT                      1077
#define IDC_GPUNAME                     1078
#define IDC_GPU_L                       1079
#define IDC_DEDICATED_L                 1080
#define IDC_SHARED_L                    1081
#define IDC_ZRECEIVESDELTA_V            1082
#define IDC_ZSENDSDELTA_V               1083
#define IDC_ZWRITESDELTA_V              1084
#define IDC_ZREADSDELTA_V               1085
#define IDC_INSTRUCTION                 1086
#define ID_EMPTY_EMPTYWORKINGSETS       40001
#define ID_EMPTY_EMPTYMODIFIEDPAGELIST  40002
#define ID_EMPTY_EMPTYSTANDBYLIST       40003
#define ID_EMPTY_EMPTYPRIORITY0STANDBYLIST 40004
#define ID_DISK_GOTOPROCESS             40005
#define ID_DISK_COPY                    40006
#define ID_DISK_PROPERTIES              40007
#define ID_DISK_OPENFILELOCATION        40008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        116
#define _APS_NEXT_COMMAND_VALUE         40009
#define _APS_NEXT_CONTROL_VALUE         1087
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
