//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NetworkTools.rc
//
#define AD_PNG                          101
#define AE_PNG                          102
#define AF_PNG                          103
#define AG_PNG                          104
#define AI_PNG                          105
#define AL_PNG                          106
#define AM_PNG                          107
#define AN_PNG                          108
#define AO_PNG                          109
#define IDD_OPTIONSKEY                  109
#define AR_PNG                          110
#define AS_PNG                          111
#define AT_PNG                          112
#define AU_PNG                          113
#define AW_PNG                          114
#define AX_PNG                          115
#define AZ_PNG                          116
#define BA_PNG                          117
#define BB_PNG                          118
#define BD_PNG                          119
#define BE_PNG                          120
#define BF_PNG                          121
#define BG_PNG                          122
#define BH_PNG                          123
#define BI__PNG                         124
#define BJ_PNG                          125
#define BM_PNG                          126
#define BN_PNG                          127
#define BO_PNG                          128
#define BR_PNG                          129
#define BS_PNG                          130
#define BT_PNG                          131
#define BV_PNG                          132
#define BW_PNG                          133
#define BY_PNG                          134
#define BZ_PNG                          135
#define CA_PNG                          136
#define AAC_PNG                         137
#define CC_PNG                          138
#define CD_PNG                          139
#define CF_PNG                          140
#define CG_PNG                          141
#define CH_PNG                          142
#define CI_PNG                          143
#define CK_PNG                          144
#define CL_PNG                          145
#define CM_PNG                          146
#define CN_PNG                          147
#define CO_PNG                          148
#define CR_PNG                          149
#define IDD_WHOIS                       149
#define CS_PNG                          150
#define IDD_PING                        150
#define CU_PNG                          151
#define IDD_OPTIONS                     151
#define CV_PNG                          152
#define IDD_TRACERT                     152
#define CX_PNG                          153
#define CY_PNG                          154
#define CZ_PNG                          155
#define DE_PNG                          156
#define DJ_PNG                          157
#define DK_PNG                          158
#define DM_PNG                          159
#define DO_PNG                          160
#define DZ_PNG                          161
#define EC_PNG                          162
#define EE_PNG                          163
#define EG_PNG                          164
#define EH_PNG                          165
#define AAD_PNG                         166
#define ER_PNG                          167
#define ES_PNG                          168
#define ET_PNG                          169
#define AAE_PNG                         170
#define AAF_PNG                         171
#define FI_PNG                          172
#define FJ_PNG                          173
#define FK_PNG                          174
#define FM_PNG                          175
#define FO_PNG                          176
#define FR_PNG                          177
#define GA_PNG                          178
#define GB_PNG                          179
#define GD_PNG                          180
#define GE_PNG                          181
#define GF_PNG                          182
#define GH_PNG                          183
#define GI_PNG                          184
#define GL_PNG                          185
#define GM_PNG                          186
#define GN_PNG                          187
#define GP_PNG                          188
#define GQ_PNG                          189
#define GR_PNG                          190
#define GS_PNG                          191
#define GT_PNG                          192
#define GU_PNG                          193
#define GW_PNG                          194
#define GY_PNG                          195
#define HK_PNG                          196
#define HM_PNG                          197
#define HN_PNG                          198
#define HR_PNG                          199
#define HT_PNG                          200
#define ID_PNG                          202
#define IE_PNG                          203
#define IL_PNG                          204
#define IN_PNG                          205
#define IO_PNG                          206
#define IQ_PNG                          207
#define IR_PNG                          208
#define IS_PNG                          209
#define IT_PNG                          210
#define JM_PNG                          211
#define JO_PNG                          212
#define JP_PNG                          213
#define KE_PNG                          214
#define KG_PNG                          215
#define KH_PNG                          216
#define KI_PNG                          217
#define KM_PNG                          218
#define KN_PNG                          219
#define KP_PNG                          220
#define KR_PNG                          221
#define KW_PNG                          222
#define KY_PNG                          223
#define KZ_PNG                          224
#define LA_PNG                          225
#define LB_PNG                          226
#define LC_PNG                          227
#define LI_PNG                          228
#define LK_PNG                          229
#define LR_PNG                          230
#define LS_PNG                          231
#define LT_PNG                          232
#define LU_PNG                          233
#define LV_PNG                          234
#define LY_PNG                          235
#define MA_PNG                          236
#define MC_PNG                          237
#define MD_PNG                          238
#define ME_PNG                          239
#define MG_PNG                          240
#define MH_PNG                          241
#define MK_PNG                          242
#define ML_PNG                          243
#define MM_PNG                          244
#define MN_PNG                          245
#define MO_PNG                          246
#define MP_PNG                          247
#define MQ_PNG                          248
#define MR_PNG                          249
#define MS_PNG                          250
#define MT_PNG                          251
#define MU_PNG                          252
#define MV_PNG                          253
#define MW_PNG                          254
#define MX_PNG                          255
#define MY_PNG                          256
#define MZ_PNG                          257
#define NA_PNG                          258
#define NC_PNG                          259
#define NE_PNG                          260
#define NF_PNG                          261
#define NG_PNG                          262
#define NI_PNG                          263
#define NL_PNG                          264
#define NO_PNG                          265
#define NP_PNG                          266
#define NR_PNG                          267
#define NU_PNG                          268
#define NZ_PNG                          269
#define OM_PNG                          270
#define PA_PNG                          271
#define PE_PNG                          272
#define PF_PNG                          273
#define PG_PNG                          274
#define PH_PNG                          275
#define PK_PNG                          276
#define PL_PNG                          277
#define PM_PNG                          278
#define PN_PNG                          279
#define PR_PNG                          280
#define PS_PNG                          281
#define PT_PNG                          282
#define PW_PNG                          283
#define PY_PNG                          284
#define QA_PNG                          285
#define RE_PNG                          286
#define RO_PNG                          287
#define RS_PNG                          288
#define RU_PNG                          289
#define RW_PNG                          290
#define SA_PNG                          291
#define SB_PNG                          292
#define SC_PNG                          293
#define AAA_PNG                         294
#define SD_PNG                          295
#define SE_PNG                          296
#define SG_PNG                          297
#define SH_PNG                          298
#define SI_PNG                          299
#define SJ_PNG                          300
#define SK_PNG                          301
#define SL_PNG                          302
#define SM_PNG                          303
#define SN_PNG                          304
#define SO_PNG                          305
#define SR_PNG                          306
#define ST_PNG                          307
#define SV_PNG                          308
#define SY_PNG                          309
#define SZ_PNG                          310
#define TC_PNG                          311
#define TD_PNG                          312
#define TF_PNG                          313
#define TG_PNG                          314
#define TH_PNG                          315
#define TJ_PNG                          316
#define TK_PNG                          317
#define TL_PNG                          318
#define TM_PNG                          319
#define TN_PNG                          320
#define TO_PNG                          321
#define TR_PNG                          322
#define TT_PNG                          323
#define TV_PNG                          324
#define TW_PNG                          325
#define TZ_PNG                          326
#define UA_PNG                          327
#define UG_PNG                          328
#define UM_PNG                          329
#define US_PNG                          330
#define UY_PNG                          331
#define UZ_PNG                          332
#define VA_PNG                          333
#define VC_PNG                          334
#define VE_PNG                          335
#define VG_PNG                          336
#define VI_PNG                          337
#define VN_PNG                          338
#define VU_PNG                          339
#define AAB_PNG                         340
#define WF_PNG                          341
#define WS_PNG                          342
#define YE_PNG                          343
#define YT_PNG                          344
#define ZA_PNG                          345
#define ZM_PNG                          346
#define ZW_PNG                          347
#define HU_PNG                          348
#define IDC_DATABASE                    1001
#define IDC_BROWSE                      1002
#define IDC_PINGPACKETLENGTH            1008
#define IDC_NETOUTPUTEDIT               1009
#define IDC_MAXHOPS                     1009
#define IDC_ICMP_PANEL                  1011
#define IDC_PINGS_LOST                  1012
#define IDC_ICMP_MIN                    1013
#define IDC_ICMP_MAX                    1014
#define IDC_ICMP_AVG                    1015
#define IDC_MAINTEXT                    1016
#define IDC_ANON_ADDR                   1017
#define IDC_ICMP_STDEV                  1018
#define IDC_PINGS_SENT                  1020
#define IDC_PING_LAYOUT                 1021
#define IDC_BAD_HASH                    1022
#define IDC_STATUS                      1023
#define IDC_GEOIP                       1028
#define IDC_LIST_TRACERT                1030
#define IDC_REFRESH                     1031
#define IDC_ENABLE_EXTENDED_TCP         1032
#define IDC_HELPLINK                    1036
#define IDC_KEYTEXT                     1037

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         40006
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
