//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ProcessHacker.rc
//
#define IDI_PROCESSHACKER               101
#define IDR_MAINWND                     102
#define IDR_MAINWND_ACCEL               102
#define IDD_PROCGENERAL                 103
#define IDD_PROCMODULES                 104
#define IDD_PROCTHREADS                 105
#define IDD_PROCHANDLES                 106
#define IDD_PROCENVIRONMENT             107
#define IDD_THRDSTACK                   108
#define IDR_THREAD                      110
#define IDR_HANDLE                      111
#define IDR_MODULE                      112
#define IDD_TERMINATOR                  114
#define IDB_CROSS                       117
#define IDB_TICK                        118
#define IDR_SHUTDOWN                    120
#define IDD_ABOUT                       121
#define IDR_PROCESS                     123
#define IDR_SERVICE                     124
#define IDD_PROCSERVICES                125
#define IDD_SRVGENERAL                  126
#define IDD_HNDLGENERAL                 128
#define IDD_INFORMATION                 129
#define IDD_FINDOBJECTS                 130
#define IDD_OBJTOKEN                    131
#define IDD_HEAPS                       132
#define IDR_PRIVILEGE                   133
#define IDR_FINDOBJ                     134
#define IDD_HIDDENPROCESSES             135
#define IDD_RUNAS                       136
#define IDD_PROGRESS                    137
#define IDD_PAGEFILES                   138
#define IDD_TOKGENERAL                  139
#define IDD_TOKADVANCED                 140
#define IDD_OBJJOB                      141
#define IDD_OBJEVENT                    142
#define IDD_OBJMUTANT                   143
#define IDD_OBJSEMAPHORE                144
#define IDD_OBJTIMER                    145
#define IDD_JOBSTATISTICS               146
#define IDD_OBJEVENTPAIR                147
#define IDD_OBJSECTION                  148
#define IDD_AFFINITY                    149
#define IDD_SYSINFO                     150
#define IDR_USER                        151
#define IDD_EDITMESSAGE                 152
#define IDD_SESSION                     153
#define IDD_PROCMEMORY                  154
#define IDC_TERMINATE                   1003
#define IDC_FILEICON                    1005
#define IDC_FILE                        1006
#define IDC_PROCESS                     1007
#define IDC_COMPANYNAME                 1009
#define IDC_VERSION                     1010
#define IDC_THRDSTACK_LIST              1013
#define IDC_REFRESH                     1015
#define IDC_PERMISSIONS                 1018
#define IDC_FILENAME                    1020
#define IDC_RUN_ALL                     1021
#define IDC_CMDLINE                     1021
#define IDC_TERMINATOR_LIST             1022
#define IDC_CURDIR                      1022
#define IDC_TERMINATOR_TEXT             1023
#define IDC_STARTED                     1023
#define IDC_ABOUT_NAME                  1024
#define IDC_PEBADDRESS                  1024
#define IDC_PARENTPROCESS               1025
#define IDC_DEP                         1026
#define IDC_PAUSE                       1027
#define IDC_PROTECTION                  1027
#define IDC_START                       1028
#define IDC_DESCRIPTION                 1029
#define IDC_TYPE                        1032
#define IDC_STARTTYPE                   1033
#define IDC_ADDRESS                     1033
#define IDC_IMPERSONATIONLEVEL          1033
#define IDC_ERRORCONTROL                1034
#define IDC_GRANTED_ACCESS              1034
#define IDC_TOKENLUID                   1034
#define IDC_GROUP                       1035
#define IDC_AUTHENTICATIONLUID          1035
#define IDC_BINARYPATH                  1036
#define IDC_MEMORYUSED                  1036
#define IDC_USERACCOUNT                 1037
#define IDC_MEMORYAVAILABLE             1037
#define IDC_PASSWORD                    1040
#define IDC_PASSWORDCHECK               1041
#define IDC_SERVICEDLL                  1042
#define IDC_NAME                        1044
#define IDC_REFERENCES                  1045
#define IDC_HANDLES                     1046
#define IDC_PROCESSTYPELABEL            1046
#define IDC_PAGED                       1047
#define IDC_PROCESSTYPETEXT             1047
#define IDC_NONPAGED                    1048
#define IDC_TEXT                        1048
#define IDC_DIAGNOSTICS                 1049
#define IDC_FILTER                      1050
#define IDC_RESULTS                     1051
#define IDC_USER                        1052
#define IDC_USERSID                     1053
#define IDC_ADVANCED                    1054
#define IDC_OWNER                       1054
#define IDC_GROUPS                      1055
#define IDC_PRIMARYGROUP                1055
#define IDC_GROUPS2                     1056
#define IDC_PRIVILEGES                  1056
#define IDC_VIRTUALIZATION              1056
#define IDC_SESSIONID                   1057
#define IDC_ELEVATED                    1058
#define IDC_VIRTUALIZED                 1059
#define IDC_SOURCENAME                  1059
#define IDC_PROPERTIES                  1060
#define IDC_SOURCELUID                  1060
#define IDC_LIST                        1061
#define IDC_SIZESINBYTES                1062
#define IDC_PROCESSES                   1063
#define IDC_SCAN                        1064
#define IDC_SAVE                        1065
#define IDC_METHOD                      1067
#define IDC_INTRO                       1068
#define IDC_PROGRAM                     1069
#define IDC_BROWSE                      1070
#define IDC_USERNAME                    1071
#define IDC_SESSIONS                    1074
#define IDC_PROGRESS                    1076
#define IDC_PROGRESSTEXT                1077
#define IDC_BUTTON1                     1079
#define IDC_LINKEDTOKEN                 1079
#define IDC_LIMITS                      1083
#define IDC_SIGNALED                    1084
#define IDC_SET                         1085
#define IDC_RESET                       1086
#define IDC_PULSE                       1087
#define IDC_COUNT                       1088
#define IDC_ABANDONED                   1089
#define IDC_CURRENTCOUNT                1090
#define IDC_MAXIMUMCOUNT                1091
#define IDC_ACQUIRE                     1092
#define IDC_RELEASE                     1093
#define IDC_CANCEL                      1094
#define IDC_OWNERLABEL                  1095
#define IDC_SETLOW                      1096
#define IDC_SETHIGH                     1097
#define IDC_SIZE_                       1098
#define IDC_CPU0                        1099
#define IDC_CPU1                        1100
#define IDC_ZSYSTEM                     1100
#define IDC_CPU2                        1101
#define IDC_CPU3                        1102
#define IDC_CPU4                        1103
#define IDC_CPU5                        1104
#define IDC_CPU6                        1105
#define IDC_CPU7                        1106
#define IDC_ZPROCESSES_L                1106
#define IDC_CPU8                        1107
#define IDC_TITLE                       1107
#define IDC_CPU9                        1108
#define IDC_CPU10                       1109
#define IDC_TIMEOUT                     1109
#define IDC_CPU11                       1110
#define IDC_CPU12                       1111
#define IDC_STATE                       1111
#define IDC_CPU13                       1112
#define IDC_CLIENTNAME                  1112
#define IDC_CPU14                       1113
#define IDC_CLIENTADDRESS               1113
#define IDC_CPU15                       1114
#define IDC_CLIENTDISPLAY               1114
#define IDC_CPU16                       1115
#define IDC_CPU17                       1116
#define IDC_CPU18                       1117
#define IDC_CPU19                       1118
#define IDC_CPU20                       1119
#define IDC_CPU21                       1120
#define IDC_CPU22                       1121
#define IDC_CPU23                       1122
#define IDC_CPU24                       1123
#define IDC_CPU25                       1124
#define IDC_CPU26                       1125
#define IDC_CPU27                       1126
#define IDC_CPU28                       1127
#define IDC_CPU29                       1128
#define IDC_CPU30                       1129
#define IDC_CPU31                       1130
#define ID_MAINWND_PROCESSTL            2001
#define ID_MAINWND_SERVICELV            2002
#define ID_MAINWND_NETWORKLV            2003
#define ID_MAINWND_PROCESSLV            2004
#define ID_HACKER_EXIT                  40001
#define ID_USERS                        40002
#define ID_TOOLS                        40003
#define ID_VIEW                         40004
#define ID_PROCESS_PROPERTIES           40006
#define ID_PROCESS_TERMINATE            40007
#define ID_PROCESS_SUSPEND              40008
#define ID_PROCESS_RESUME               40009
#define ID_HACKER_SAVE                  40010
#define ID_THREAD_TERMINATE             40011
#define ID_THREAD_SUSPEND               40012
#define ID_THREAD_RESUME                40013
#define ID_THREAD_FORCETERMINATE        40014
#define ID_THREAD_PERMISSIONS           40015
#define ID_THREAD_TOKEN                 40016
#define ID_THREAD_ANALYZE               40017
#define ID_ANALYZE_WAIT                 40018
#define ID_THREAD_PRIORITY              40019
#define ID_PRIORITY_TIMECRITICAL        40020
#define ID_PRIORITY_HIGHEST             40021
#define ID_PRIORITY_ABOVENORMAL         40022
#define ID_PRIORITY_NORMAL              40023
#define ID_PRIORITY_BELOWNORMAL         40024
#define ID_PRIORITY_LOWEST              40025
#define ID_PRIORITY_IDLE                40026
#define ID_THREAD_I                     40027
#define ID_I_0                          40028
#define ID_I_1                          40029
#define ID_I_2                          40030
#define ID_I_3                          40031
#define ID_PROCESS_RESTART              40032
#define ID_PROCESS_REDUCEWORKINGSET     40033
#define ID_PROCESS_VIRTUALIZATION       40034
#define ID_PROCESS_AFFINITY             40035
#define ID_PROCESS_CREATEDUMPFILE       40036
#define ID_PROCESS_TERMINATOR           40037
#define ID_PROCESS_MISCELLANEOUS        40038
#define ID_MISCELLANEOUS_DETACHFROMDEBUGGER 40039
#define ID_MISCELLANEOUS_HEAPS          40040
#define ID_MISCELLANEOUS_INJECTDLL      40041
#define ID_MISCELLANEOUS_I              40042
#define ID_PROCESS_PRIORITY             40047
#define ID_PRIORITY_REALTIME            40048
#define ID_PRIORITY_HIGH                40049
#define ID_PROCESS_WINDOW               40054
#define ID_WINDOW_BRINGTOFRONT          40055
#define ID_WINDOW_RESTORE               40056
#define ID_WINDOW_MINIMIZE              40057
#define ID_WINDOW_MAXIMIZE              40058
#define ID_WINDOW_CLOSE                 40059
#define ID_PROCESS_SEARCHONLINE         40060
#define ID_HANDLE_CLOSE                 40061
#define ID_HANDLE_PROTECTED             40062
#define ID_HANDLE_INHERIT               40063
#define ID_HANDLE_PROPERTIES            40064
#define ID_MODULE_UNLOAD                40066
#define ID_MODULE_OPENCONTAININGFOLDER  40067
#define ID_MODULE_PROPERTIES            40068
#define ID_PROCESS_TERMINATETREE        40069
#define ID_THREAD_INSPECT               40075
#define ID_HACKER_RUN                   40076
#define ID_HACKER_RUNASADMINISTRATOR    40077
#define ID_HACKER_RUNAS                 40078
#define ID_HACKER_SHOWDETAILSFORALLPROCESSES 40079
#define ID_HACKER_0                     40080
#define ID_HACKER_OPEN                  40081
#define ID_HACKER_FINDHANDLESORDLLS     40082
#define ID_HACKER_OPTIONS               40083
#define ID_SHUTDOWN_LOCK                40084
#define ID_SHUTDOWN_LOGOFF              40085
#define ID_SHUTDOWN_SLEEP               40086
#define ID_SHUTDOWN_HIBERNATE           40087
#define ID_SHUTDOWN_RESTART             40088
#define ID_SHUTDOWN_SHUTDOWN            40089
#define ID_SHUTDOWN_POWEROFF            40090
#define ID_VIEW_SYSTEMINFORMATION       40091
#define ID_VIEW_TRAYICONS               40092
#define ID_TRAYICONS_CPUHISTORY         40093
#define ID_TRAYICONS_CPUUSAGE           40094
#define ID_TRAYICONS_I                  40095
#define ID_TRAYICONS_COMMITHISTORY      40096
#define ID_TRAYICONS_PHYSICALMEMORYHISTORY 40097
#define ID_VIEW_REFRESH                 40098
#define ID_VIEW_UPDATEPROCESSES         40099
#define ID_VIEW_UPDATESERVICES          40100
#define ID_TOOLS_CREATESERVICE          40101
#define ID_TOOLS_HIDDENPROCESSES        40102
#define ID_TOOLS_VERIFYFILESIGNATURE    40103
#define ID_HELP_LOG                     40104
#define ID_HELP_DONATE                  40105
#define ID_HELP_ABOUT                   40106
#define ID_SERVICE_GOTOPROCESS          40107
#define ID_SERVICE_START                40108
#define ID_SERVICE_CONTINUE             40109
#define ID_SERVICE_PAUSE                40110
#define ID_SERVICE_STOP                 40111
#define ID_SERVICE_DELETE               40112
#define ID_SERVICE_PROPERTIES           40113
#define ID_PRIVILEGE_ENABLE             40116
#define ID_PRIVILEGE_DISABLE            40117
#define ID_PRIVILEGE_REMOVE             40118
#define ID_OBJECT_CLOSE                 40119
#define ID_OBJECT_PROPERTIES            40120
#define ID_OBJECT_PROCESSPROPERTIES     40121
#define ID_HELP_DEBUGCONSOLE            40122
#define ID_MODULE_SEARCHONLINE          40125
#define ID_TOOLS_PAGEFILES              40126
#define ID_USER_DISCONNECT              40127
#define ID_USER_LOGOFF                  40128
#define ID_USER_SENDMESSAGE             40129
#define ID_USER_PROPERTIES              40130
#define ID_USERS_DUMMY                  40131
#define ID_MODULE_INSPECT               40132
#define IDDYNAMIC                       50000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         40133
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
