//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SystemInformer.rc
//
#define IDI_PROCESSHACKER               101
#define IDR_MAINWND_ACCEL               102
#define IDD_PROCGENERAL                 103
#define IDD_PROCMODULES                 104
#define IDD_PROCTHREADS                 105
#define IDD_PROCHANDLES                 106
#define IDD_PROCENVIRONMENT             107
#define IDD_THRDSTACK                   108
#define IDC_CPU                         112
#define IDC_PRIVATEBYTES                113
#define IDC_IO                          114
#define IDB_CROSS                       117
#define IDB_TICK                        118
#define IDC_MEMORY                      120
#define IDD_ABOUT                       121
#define IDC_NEWOBJECTS                  121
#define IDC_REMOVEDOBJECTS              122
#define IDD_SRVLIST                     125
#define IDD_SRVGENERAL                  126
#define IDD_HNDLGENERAL                 128
#define IDD_INFORMATION                 129
#define IDD_FINDOBJECTS                 130
#define IDD_OBJTOKEN                    131
#define ID_PLUGIN_MENU_ITEM             131
#define IDD_HIDDENPROCESSES             135
#define ID_TRAYICONS_REGISTERED         135
#define IDD_RUNAS                       136
#define ID_COPY_CELL                    136
#define IDD_PROGRESS                    137
#define IDD_PAGEFILES                   138
#define IDD_TOKGENERAL                  139
#define IDD_TOKADVANCED                 140
#define IDD_OBJJOB                      141
#define IDD_OBJEVENT                    142
#define IDD_OBJMUTANT                   143
#define IDD_OBJSEMAPHORE                144
#define IDD_OBJTIMER                    145
#define IDD_JOBSTATISTICS               146
#define IDD_OBJEVENTPAIR                147
#define IDD_OBJSECTION                  148
#define IDD_AFFINITY                    149
#define IDD_SYSINFO                     150
#define IDD_EDITMESSAGE                 152
#define IDD_SESSION                     153
#define IDD_PROCMEMORY                  154
#define IDD_CHOOSE                      155
#define IDD_OPTGENERAL                  162
#define IDD_OPTHIGHLIGHTING             163
#define IDD_CHOOSECOLUMNS               166
#define IDD_NETSTACK                    167
#define IDD_CREATESERVICE               168
#define IDD_PROCPERFORMANCE             169
#define ID_SHOWCONTEXTMENU              169
#define IDD_PROCSTATISTICS              170
#define IDD_OPTADVANCED                 171
#define IDD_GDIHANDLES                  175
#define IDD_LOG                         178
#define IDD_MEMEDIT                     180
#define IDD_MEMPROTECT                  182
#define IDD_MEMRESULTS                  183
#define IDD_MEMSTRING                   185
#define IDD_OPTGRAPHS                   186
#define IDD_PLUGINS                     187
#define IDD_PLUGINMANAGER               187
#define IDD_HANDLESTATS                 188
#define IDD_PROCRECORD                  189
#define IDD_CHOOSEPROCESS               190
#define IDD_PROCSERVICES                191
#define IDI_PHAPPLICATION               191
#define IDI_COG                         192
#define IDD_SHADOWSESSION               193
#define IDI_PHAPPLICATIONGO             194
#define IDD_TOKCAPABILITIES             194
#define IDI_COGGO                       195
#define IDD_TOKATTRIBUTES               195
#define IDD_SYSINFO_CPU                 196
#define IDD_SYSINFO_CPUPANEL            197
#define IDD_SYSINFO_MEMPANEL            198
#define IDR_SYSINFO_ACCEL               198
#define IDD_SYSINFO_MEM                 199
#define IDD_SYSINFO_IO                  200
#define IDD_SYSINFO_IOPANEL             201
#define IDD_MEMLISTS                    202
#define IDD_CONTAINER                   205
#define IDD_MINIINFO                    207
#define IDD_MINIINFO_LIST               210
#define IDD_MITIGATION                  215
#define IDI_PIN                         216
#define IDI_FOLDER                      217
#define IDI_PENCIL                      218
#define IDI_MAGNIFIER                   219
#define IDD_EDITENV                     221
#define IDB_SEARCH_ACTIVE               223
#define IDB_SEARCH_INACTIVE             224
#define IDB_SEARCH_ACTIVE_BMP           225
#define IDB_SEARCH_INACTIVE_BMP         226
#define IDD_OPTIONS                     227
#define IDD_PLUGINPROPERTIES            228
#define IDD_PLUGINSDISABLED             241
#define IDD_PROCWMIPROVIDERS            242
#define IDD_COLUMNSETS                  243
#define ID_VIEW_TRAYICONS               244
#define IDD_OBJFILE                     249
#define IDD_RUNFILEDLG                  253
#define IDD_LIVEDUMP                    254
#define IDD_HEAPS                       255
#define IDD_PROCVDMHOST                 257
#define IDD_OPTSYMBOLS                  258
#define IDI_UACSHIELD                   261
#define IDC_TERMINATE                   1003
#define IDC_FILEICON                    1005
#define IDC_FILE                        1006
#define IDC_PROCESS                     1007
#define IDC_COMPANYNAME                 1009
#define IDC_VERSION                     1010
#define IDC_REFRESH                     1015
#define IDC_PERMISSIONS                 1018
#define IDC_FILENAME                    1020
#define IDC_CMDLINE                     1021
#define IDC_URL                         1021
#define IDC_RUNSELECTED                 1021
#define IDC_CURDIR                      1022
#define IDC_STARTED                     1023
#define IDC_ABOUT_NAME                  1024
#define IDC_TERMINATED                  1024
#define IDC_PARENTCONSOLE               1024
#define IDC_PARENTPROCESS               1025
#define IDC_MITIGATION                  1026
#define IDC_PAUSE                       1027
#define IDC_PROTECTION                  1027
#define IDC_START                       1028
#define IDC_FILENAMEWIN32               1028
#define IDC_DESCRIPTION                 1029
#define IDC_TYPE                        1032
#define IDC_STARTTYPE                   1033
#define IDC_ADDRESS                     1033
#define IDC_IMPERSONATIONLEVEL          1033
#define IDC_ERRORCONTROL                1034
#define IDC_GRANTED_ACCESS              1034
#define IDC_TOKENLUID                   1034
#define IDC_GROUP                       1035
#define IDC_AUTHENTICATIONLUID          1035
#define IDC_BINARYPATH                  1036
#define IDC_MEMORYUSED                  1036
#define IDC_USERACCOUNT                 1037
#define IDC_MEMORYAVAILABLE             1037
#define IDC_PASSWORD                    1040
#define IDC_PASSWORDCHECK               1041
#define IDC_SERVICEDLL                  1042
#define IDC_NAME                        1044
#define IDC_REFERENCES                  1045
#define IDC_INTERNALNAME                1045
#define IDC_HANDLES                     1046
#define IDC_AUTHOR                      1046
#define IDC_PAGED                       1047
#define IDC_PROCESSTYPETEXT             1047
#define IDC_NONPAGED                    1048
#define IDC_TEXT                        1048
#define IDC_DIAGNOSTICS                 1049
#define IDC_FILTER                      1050
#define IDC_RESULTS                     1051
#define IDC_USER                        1052
#define IDC_USERSID                     1053
#define IDC_ADVANCED                    1054
#define IDC_OWNER                       1054
#define IDC_GROUPS                      1055
#define IDC_PRIMARYGROUP                1055
#define IDC_VIRTUALIZATION              1056
#define IDC_SESSIONID                   1057
#define IDC_ELEVATED                    1058
#define IDC_VIRTUALIZED                 1059
#define IDC_SOURCENAME                  1059
#define IDC_PROPERTIES                  1060
#define IDC_SOURCELUID                  1060
#define IDC_APPCONTAINERSID             1060
#define IDC_LIST                        1061
#define IDC_TOKENUSER                   1061
#define IDC_UIACCESS                    1061
#define IDC_TOKENSID                    1062
#define IDC_PROCESSES                   1063
#define IDC_SCAN                        1064
#define IDC_SAVE                        1065
#define IDC_METHOD                      1067
#define IDC_INTRO                       1068
#define IDC_PROGRAM                     1069
#define IDC_BROWSE                      1070
#define IDC_USERNAME                    1071
#define IDC_SESSIONCOMBO                1072
#define IDC_DESKTOPCOMBO                1073
#define IDC_SESSIONS                    1074
#define IDC_PROGRAMCOMBO                1074
#define IDC_DESKTOPS                    1075
#define IDC_PROGRESS                    1076
#define IDC_PROGRESSTEXT                1077
#define IDC_LINKEDTOKEN                 1079
#define IDC_DISABLEALL                  1079
#define IDC_MOVEUP                      1079
#define IDC_CLEAR                       1079
#define IDC_GOTO                        1079
#define IDC_OPTIONS                     1079
#define IDC_DETAILS                     1079
#define IDC_ADD                         1079
#define IDC_FONT                        1079
#define IDC_INTEGRITY                   1079
#define IDC_MORE                        1079
#define IDC_VIEWMITIGATION              1080
#define IDC_REPLACETASKMANAGER          1080
#define IDC_RENAME                      1080
#define IDC_VIEWPARENTPROCESS           1081
#define IDC_OPENFILENAME                1082
#define IDC_LIMITS                      1083
#define IDC_OPENFILENAME2               1083
#define IDC_SIGNALED                    1084
#define IDC_SET                         1085
#define IDC_RESET                       1086
#define IDC_PULSE                       1087
#define IDC_APPLY                       1087
#define IDC_COUNT                       1088
#define IDC_ABANDONED                   1089
#define IDC_CURRENTCOUNT                1090
#define IDC_MAXIMUMCOUNT                1091
#define IDC_ACQUIRE                     1092
#define IDC_RELEASE                     1093
#define IDC_CANCEL                      1094
#define IDC_OWNERLABEL                  1095
#define IDC_SETLOW                      1096
#define IDC_SETHIGH                     1097
#define IDC_SIZE_                       1098
#define IDC_CPU0                        1099
#define IDC_CPU1                        1100
#define IDC_CPU2                        1101
#define IDC_CPU3                        1102
#define IDC_CPU4                        1103
#define IDC_CPU5                        1104
#define IDC_CPU6                        1105
#define IDC_CPU7                        1106
#define IDC_CPU8                        1107
#define IDC_TITLE                       1107
#define IDC_CPU9                        1108
#define IDC_CPU10                       1109
#define IDC_TIMEOUT                     1109
#define IDC_CPU11                       1110
#define IDC_CPU12                       1111
#define IDC_STATE                       1111
#define IDC_CPU13                       1112
#define IDC_CLIENTNAME                  1112
#define IDC_CPU14                       1113
#define IDC_CLIENTADDRESS               1113
#define IDC_CPU15                       1114
#define IDC_CLIENTDISPLAY               1114
#define IDC_CPU16                       1115
#define IDC_CHOICE                      1115
#define IDC_CPU17                       1116
#define IDC_OPTION                      1116
#define IDC_CPU18                       1117
#define IDC_CHOICEUSER                  1117
#define IDC_CPU19                       1118
#define IDC_HIDEUNNAMEDHANDLES          1118
#define IDC_CPU20                       1119
#define IDC_CPU21                       1120
#define IDC_STARTMODULE                 1120
#define IDC_CPU22                       1121
#define IDC_OPENSTARTMODULE             1121
#define IDC_CPU23                       1122
#define IDC_KERNELTIME                  1122
#define IDC_CPU24                       1123
#define IDC_USERTIME                    1123
#define IDC_CPU25                       1124
#define IDC_CONTEXTSWITCHES             1124
#define IDC_CPU26                       1125
#define IDC_CYCLES                      1125
#define IDC_CPU27                       1126
#define IDC_PRIORITY                    1126
#define IDC_CPU28                       1127
#define IDC_BASEPRIORITY                1127
#define IDC_CPU29                       1128
#define IDC_IOPRIORITY                  1128
#define IDC_CPU30                       1129
#define IDC_PAGEPRIORITY                1129
#define IDC_CPU31                       1130
#define IDC_STATICBL1                   1130
#define IDC_STATICBL2                   1131
#define IDC_CPU32                       1131
#define IDC_STATICBL3                   1132
#define IDC_CPU33                       1132
#define IDC_STATICBL4                   1133
#define IDC_CPU34                       1133
#define IDC_STATICBL5                   1134
#define IDC_CPU35                       1134
#define IDC_STATICBL6                   1135
#define IDC_CPU36                       1135
#define IDC_STATICBL7                   1136
#define IDC_CPU37                       1136
#define IDC_STATICBL8                   1137
#define IDC_CPU38                       1137
#define IDC_STATICBL9                   1138
#define IDC_CPU39                       1138
#define IDC_STATICBL10                  1139
#define IDC_CPU40                       1139
#define IDC_STATICBL11                  1140
#define IDC_CPU41                       1140
#define IDC_CHOICESIMPLE                1141
#define IDC_CPU42                       1141
#define IDC_MESSAGE                     1142
#define IDC_CPU43                       1142
#define IDC_SEARCHENGINE                1143
#define IDC_CPU44                       1143
#define IDC_MAXSIZEUNIT                 1144
#define IDC_CPU45                       1144
#define IDC_CPU46                       1145
#define IDC_CPU47                       1146
#define IDC_CPU48                       1147
#define IDC_CPU49                       1148
#define IDC_CPU50                       1149
#define IDC_CPU51                       1150
#define IDC_PEVIEWER                    1151
#define IDC_CPU52                       1151
#define IDC_CPU53                       1152
#define IDC_CPU54                       1153
#define IDC_CPU55                       1154
#define IDC_HIGHLIGHTINGDURATION        1155
#define IDC_CPU56                       1155
#define IDC_CPU57                       1156
#define IDC_ENABLEALL                   1157
#define IDC_CPU58                       1157
#define IDC_ZACTIVEPROCESSES_V          1158
#define IDC_CPU59                       1158
#define IDC_ZTOTALPROCESSES_V           1159
#define IDC_CPU60                       1159
#define IDC_ZTERMINATEDPROCESSES_V      1160
#define IDC_CPU61                       1160
#define IDC_ZUSERTIME_V                 1161
#define IDC_CPU62                       1161
#define IDC_ZKERNELTIME_V               1162
#define IDC_CPU63                       1162
#define IDC_ZUSERTIMEPERIOD_V           1163
#define IDC_ZKERNELTIMEPERIOD_V         1164
#define IDC_ZPAGEFAULTS_V               1165
#define IDC_ZPEAKPROCESSUSAGE_V         1166
#define IDC_ZPEAKJOBUSAGE_V             1167
#define IDC_ZIOREADS_V                  1168
#define IDC_ZIOREADBYTES_V              1169
#define IDC_ZIOWRITES_V                 1170
#define IDC_ZIOWRITEBYTES_V             1171
#define IDC_ZIOOTHER_V                  1172
#define IDC_ZIOOTHERBYTES_V             1173
#define IDC_MOVEDOWN                    1176
#define IDC_REMOVE                      1177
#define IDC_DISPLAYNAME                 1179
#define IDC_ZPRIORITY_V                 1181
#define IDC_ZCYCLES_V                   1182
#define IDC_ZTOTALTIME_V                1185
#define IDC_ZPRIVATEBYTES_V             1186
#define IDC_ZWORKINGSET_V               1187
#define IDC_ZPEAKWORKINGSET_V           1188
#define IDC_ZVIRTUALSIZE_V              1189
#define IDC_ZPEAKVIRTUALSIZE_V          1190
#define IDC_ZPEAKPRIVATEBYTES_V         1191
#define IDC_ZPAGEPRIORITY_V             1192
#define IDC_ZIOPRIORITY_V               1194
#define IDC_ZHANDLES_V                  1195
#define IDC_ZGDIHANDLES_V               1196
#define IDC_ZOTHERDELTA_V               1196
#define IDC_ZUSERHANDLES_V              1197
#define IDC_ZOTHER_V                    1197
#define IDC_GROUPCPU                    1198
#define IDC_GROUPPRIVATEBYTES           1199
#define IDC_GROUPIO                     1200
#define IDC_ONEGRAPHPERCPU              1202
#define IDC_ALWAYSONTOP                 1203
#define IDC_COPY                        1206
#define IDC_INACTIVE                    1207
#define IDC_ACTIVE                      1208
#define IDC_SHOW                        1209
#define IDC_HIDE                        1210
#define IDC_AUTOSCROLL                  1215
#define IDC_UNDECORATESYMBOLS           1216
#define IDC_DBGHELPPATH                 1217
#define IDC_DBGHELPSEARCHPATH           1218
#define IDC_DESKTOP                     1221
#define IDC_REREAD                      1224
#define IDC_WRITE                       1225
#define IDC_VALUE                       1230
#define IDC_DELAYEDSTART                1234
#define IDC_MINIMUMLENGTH               1236
#define IDC_DETECTUNICODE               1237
#define IDC_PRIVATE                     1238
#define IDC_IMAGE                       1239
#define IDC_MAPPED                      1240
#define IDC_EXTENDEDUNICODE             1241
#define IDC_SHOWTEXT                    1245
#define IDC_ICONPROCESSES               1248
#define IDC_CLEANUP                     1251
#define IDC_TOGGLEELEVATION             1254
#define IDC_TOGGLESUSPENDED             1255
#define IDC_TRUSTEDINSTALLER            1255
#define IDC_PARENT                      1263
#define IDC_PROCESSNAME                 1264
#define IDC_SERVICES_LAYOUT             1266
#define IDC_LINK_SF                     1267
#define IDC_CREDITS                     1270
#define IDC_LOGONTIME                   1272
#define IDC_ZPEAKHANDLES_V              1273
#define IDC_SHIFT                       1274
#define IDC_USEOLDCOLORS                1274
#define IDC_OPENURL                     1279
#define IDC_COMPANYNAME_LINK            1279
#define IDC_SAMPLECOUNT                 1280
#define IDC_SAMPLECOUNTLABEL            1281
#define IDC_VIRTUALKEY                  1283
#define IDC_CTRL                        1284
#define IDC_ALT                         1285
#define IDC_CONNECTTIME                 1286
#define IDC_DISCONNECTTIME              1287
#define IDC_LASTINPUTTIME               1288
#define IDC_ZPRIVATEWS_V                1289
#define IDC_ZSHAREABLEWS_V              1290
#define IDC_ZSHAREDWS_V                 1291
#define IDC_IDEALPROCESSOR              1294
#define IDC_STATICBL12                  1295
#define IDC_BASICINFORMATION            1296
#define IDC_INSTRUCTION                 1298
#define IDC_CPUNAME                     1299
#define IDC_LAYOUT                      1300
#define IDC_UTILIZATION                 1301
#define IDC_SPEED                       1302
#define IDC_ZPROCESSES_V                1303
#define IDC_ZTHREADS_V                  1304
#define IDC_ZCONTEXTSWITCHESDELTA_V     1307
#define IDC_ZINTERRUPTSDELTA_V          1308
#define IDC_ZDPCSDELTA_V                1309
#define IDC_ZSYSTEMCALLSDELTA_V         1310
#define IDC_GRAPH_LAYOUT                1311
#define IDC_ZCORES                      1311
#define IDC_TOTALPHYSICAL               1312
#define IDC_ZSOCKETS                    1312
#define IDC_ZLOGICAL                    1313
#define IDC_ZCOMMITCURRENT_V            1314
#define IDC_ZLATENCY                    1314
#define IDC_ZCOMMITPEAK_V               1315
#define IDC_ZCOMMITLIMIT_V              1316
#define IDC_ZPHYSICALCURRENT_V          1317
#define IDC_ZPHYSICALTOTAL_V            1318
#define IDC_ZPHYSICALCACHEWS_V          1319
#define IDC_ZPHYSICALKERNELWS_V         1320
#define IDC_ZPHYSICALDRIVERWS_V         1321
#define IDC_ZPAGEDWORKINGSET_V          1322
#define IDC_ZPAGEDVIRTUALSIZE_V         1323
#define IDC_ZPAGEDLIMIT_V               1324
#define IDC_ZPAGEDALLOCSDELTA_V         1325
#define IDC_ZPAGEDFREESDELTA_V          1326
#define IDC_ZNONPAGEDUSAGE_V            1327
#define IDC_ZNONPAGEDLIMIT_V            1328
#define IDC_ZNONPAGEDALLOCSDELTA_V      1329
#define IDC_ZNONPAGEDFREESDELTA_V       1330
#define IDC_ZPHYSICALRESERVED_V         1331
#define IDC_ZLISTZEROED_V               1332
#define IDC_ZLISTFREE_V                 1333
#define IDC_ZLISTMODIFIED_V             1334
#define IDC_ZLISTMODIFIEDNOWRITE_V      1335
#define IDC_ZLISTSTANDBY_V              1337
#define IDC_COMMIT_L                    1339
#define IDC_PHYSICAL_L                  1340
#define IDC_ZUPTIME_V                   1341
#define IDC_ZOTHERBYTESDELTA_V          1342
#define IDC_ZREADSDELTA_V               1343
#define IDC_ZREADBYTESDELTA_V           1344
#define IDC_ZWRITESDELTA_V              1345
#define IDC_ZLISTSTANDBY0_V             1346
#define IDC_ZWRITEBYTESDELTA_V          1346
#define IDC_ZLISTSTANDBY1_V             1347
#define IDC_ZREADS_V                    1347
#define IDC_ZLISTSTANDBY2_V             1348
#define IDC_ZREADBYTES_V                1348
#define IDC_ZLISTSTANDBY3_V             1349
#define IDC_ZWRITES_V                   1349
#define IDC_ZLISTBAD_V                  1350
#define IDC_ZWRITEBYTES_V               1350
#define IDC_ZLISTREPURPOSED_V           1351
#define IDC_ZOTHERBYTES_V               1351
#define IDC_ZLISTREPURPOSED0_V          1352
#define IDC_ZLISTREPURPOSED1_V          1353
#define IDC_ZLISTREPURPOSED2_V          1354
#define IDC_ZLISTREPURPOSED3_V          1355
#define IDC_ZLISTREPURPOSED4_V          1356
#define IDC_ZLISTREPURPOSED5_V          1357
#define IDC_ZLISTREPURPOSED6_V          1358
#define IDC_ZLISTREPURPOSED7_V          1359
#define IDC_EMPTY                       1360
#define IDC_SAMPLECOUNTAUTOMATIC        1361
#define IDC_SHOWCOMMITINSUMMARY         1361
#define IDC_ZLISTSTANDBY4_V             1364
#define IDC_ZLISTSTANDBY5_V             1365
#define IDC_SELECTALL                   1365
#define IDC_ZLISTSTANDBY6_V             1366
#define IDC_DESELECTALL                 1366
#define IDC_ZLISTSTANDBY7_V             1367
#define IDC_INSPECT                     1367
#define IDC_ZPAGINGPAGEFAULTSDELTA_V    1368
#define IDC_INSPECT2                    1368
#define IDC_ZPAGINGPAGEREADSDELTA_V     1369
#define IDC_BYTESPERROW                 1369
#define IDC_ZPAGINGPAGEFILEWRITESDELTA_V 1370
#define IDC_PINWINDOW                   1370
#define IDC_ZPAGINGMAPPEDWRITESDELTA_V  1371
#define IDC_ZMAPPEDREADIO               1372
#define IDC_ZLISTMODIFIEDPAGEFILE_V     1373
#define IDC_ZMAPPEDWRITEIO              1374
#define IDC_SECTION                     1375
#define IDC_REGEX                       1377
#define IDC_DESCRIPTIONLABEL            1378
#define IDC_VIEWCOMMANDLINE             1381
#define IDC_DELETE                      1382
#define IDC_EDIT                        1383
#define IDC_NEW                         1384
#define IDC_HANDLESEARCH                1385
#define IDC_SEARCH                      1387
#define IDC_FILTEROPTIONS               1389
#define IDC_FILTERTYPE                  1390
#define IDC_TREELIST                    1391
#define IDC_SECTIONTREE                 1393
#define IDC_INFO                        1396
#define IDC_DEFSTATE                    1398
#define IDC_SETTINGS                    1399
#define IDC_PLUGINTREE                  1400
#define IDC_DISABLED                    1401
#define IDC_LIST_DISABLED               1402
#define IDC_COLUMNSETLIST               1403
#define IDC_STATISTICS_LIST             1404
#define IDC_FLUSH                       1406
#define IDC_POSITION                    1407
#define IDC_FILESIZE                    1408
#define IDC_FILETYPE                    1409
#define IDC_FILEMODE                    1410
#define IDC_DEFAULTPERM                 1410
#define IDC_DUMPSTACK                   1411
#define IDC_COMPRESS                    1412
#define IDC_USERMODE                    1413
#define IDC_HYPERVISOR                  1414
#define IDC_SIZESINBYTES                1415
#define IDC_FONTMONOSPACE               1416
#define ID_HACKER_EXIT                  40001
#define ID_PROCESS_PROPERTIES           40006
#define ID_PROCESS_TERMINATE            40007
#define ID_PROCESS_SUSPEND              40008
#define ID_PROCESS_RESUME               40009
#define ID_HACKER_SAVE                  40010
#define ID_THREAD_TERMINATE             40011
#define ID_THREAD_SUSPEND               40012
#define ID_THREAD_RESUME                40013
#define ID_THREAD_PERMISSIONS           40015
#define ID_THREAD_TOKEN                 40016
#define ID_ANALYZE_WAIT                 40018
#define ID_PRIORITY_TIMECRITICAL        40020
#define ID_PRIORITY_HIGHEST             40021
#define ID_PRIORITY_ABOVENORMAL         40022
#define ID_PRIORITY_NORMAL              40023
#define ID_PRIORITY_BELOWNORMAL         40024
#define ID_PRIORITY_LOWEST              40025
#define ID_PRIORITY_IDLE                40026
#define ID_IOPRIORITY_VERYLOW           40028
#define ID_IOPRIORITY_LOW               40029
#define ID_IOPRIORITY_NORMAL            40030
#define ID_IOPRIORITY_HIGH              40031
#define ID_PROCESS_RESTART              40032
#define ID_PROCESS_VIRTUALIZATION       40034
#define ID_PROCESS_AFFINITY             40035
#define ID_PROCESS_CREATEDUMPFILE       40036
#define ID_PROCESS_PRIORITY             40037
#define ID_MISCELLANEOUS_SETCRITICAL    40038
#define ID_MISCELLANEOUS_DETACHFROMDEBUGGER 40039
#define ID_PROCESS_IOPRIORITY           40040
#define ID_PROCESS_MISCELLANEOUS        40041
#define ID_PROCESS_WINDOW               40042
#define ID_PROCESS_PAGEPRIORITY         40043
#define ID_PROCESS_BOOST                40044
#define ID_PRIORITY_REALTIME            40048
#define ID_PRIORITY_HIGH                40049
#define ID_MISCELLANEOUS_ECOMODE        40050
#define ID_WINDOW_BRINGTOFRONT          40055
#define ID_WINDOW_RESTORE               40056
#define ID_WINDOW_MINIMIZE              40057
#define ID_WINDOW_MAXIMIZE              40058
#define ID_WINDOW_CLOSE                 40059
#define ID_PROCESS_SEARCHONLINE         40060
#define ID_HANDLE_CLOSE                 40061
#define ID_HANDLE_PROTECTED             40062
#define ID_HANDLE_INHERIT               40063
#define ID_HANDLE_PROPERTIES            40064
#define ID_HANDLE_SECURITY              40065
#define ID_MODULE_UNLOAD                40066
#define ID_MODULE_PROPERTIES            40068
#define ID_PROCESS_TERMINATETREE        40069
#define ID_PROCESS_SUSPENDTREE          40070
#define ID_PROCESS_RESUMETREE           40071
#define ID_THREAD_INSPECT               40075
#define ID_HACKER_RUN                   40076
#define ID_HACKER_RUNASADMINISTRATOR    40077
#define ID_HACKER_RUNAS                 40078
#define ID_HACKER_SHOWDETAILSFORALLPROCESSES 40079
#define ID_HACKER_FINDHANDLESORDLLS     40082
#define ID_HACKER_OPTIONS               40083
#define ID_PROCESS_FREEZE               40084
#define ID_PROCESS_THAW                 40085
#define ID_VIEW_SYSTEMINFORMATION       40091
#define ID_TRAYICONS_CPUHISTORY         40093
#define ID_TRAYICONS_CPUUSAGE           40094
#define ID_TRAYICONS_COMMITHISTORY      40096
#define ID_TRAYICONS_PHYSICALMEMORYHISTORY 40097
#define ID_VIEW_REFRESH                 40098
#define ID_TOOLS_CREATESERVICE          40101
#define ID_TOOLS_HIDDENPROCESSES        40102
#define ID_TOOLS_INSPECTEXECUTABLEFILE  40103
#define ID_HELP_LOG                     40104
#define ID_HELP_DONATE                  40105
#define ID_HELP_ABOUT                   40106
#define ID_SERVICE_GOTOPROCESS          40107
#define ID_SERVICE_START                40108
#define ID_SERVICE_CONTINUE             40109
#define ID_SERVICE_PAUSE                40110
#define ID_SERVICE_STOP                 40111
#define ID_SERVICE_DELETE               40112
#define ID_SERVICE_PROPERTIES           40113
#define ID_SERVICE_OPENKEY              40114
#define ID_PRIVILEGE_ENABLE             40116
#define ID_PRIVILEGE_DISABLE            40117
#define ID_PRIVILEGE_REMOVE             40118
#define ID_OBJECT_CLOSE                 40119
#define ID_OBJECT_PROPERTIES            40120
#define ID_HELP_DEBUGCONSOLE            40122
#define ID_TOOLS_PAGEFILES              40126
#define ID_USER_DISCONNECT              40127
#define ID_USER_LOGOFF                  40128
#define ID_USER_SENDMESSAGE             40129
#define ID_USER_PROPERTIES              40130
#define ID_USERS_DUMMY                  40131
#define ID_PROCESS_DEBUG                40133
#define ID_USER_CONNECT                 40138
#define ID_NETWORK_GOTOPROCESS          40139
#define ID_NETWORK_CLOSE                40140
#define ID_OPACITY_10                   40142
#define ID_OPACITY_20                   40143
#define ID_OPACITY_30                   40144
#define ID_OPACITY_40                   40145
#define ID_OPACITY_50                   40146
#define ID_OPACITY_60                   40147
#define ID_OPACITY_70                   40148
#define ID_OPACITY_80                   40149
#define ID_OPACITY_90                   40150
#define ID_OPACITY_OPAQUE               40151
#define ID_VIEW_ALWAYSONTOP             40153
#define ID_UPDATEINTERVAL_FAST          40155
#define ID_UPDATEINTERVAL_NORMAL        40156
#define ID_UPDATEINTERVAL_BELOWNORMAL   40157
#define ID_UPDATEINTERVAL_SLOW          40158
#define ID_UPDATEINTERVAL_VERYSLOW      40159
#define ID_COMPUTER_LOCK                40160
#define ID_COMPUTER_LOGOFF              40161
#define ID_COMPUTER_SLEEP               40162
#define ID_COMPUTER_HIBERNATE           40163
#define ID_COMPUTER_RESTART             40164
#define ID_COMPUTER_SHUTDOWN            40165
#define ID_COMPUTER_RESTART_NATIVE      40166
#define ID_COMPUTER_SHUTDOWN_NATIVE     40167
#define ID_COMPUTER_RESTART_CRITICAL    40168
#define ID_COMPUTER_SHUTDOWN_CRITICAL   40169
#define ID_COMPUTER_RESTART_UPDATE      40170
#define ID_COMPUTER_SHUTDOWN_UPDATE     40171
#define ID_TRAYICONS_IOHISTORY          40172
#define ID_ICON_EXIT                    40173
#define ID_ICON_SHOWHIDEPROCESSHACKER   40174
#define ID_ICON_SYSTEMINFORMATION       40175
#define ID_PROCESSES_DUMMY              40177
#define ID_NOTIFICATIONS_ENABLEALL      40178
#define ID_NOTIFICATIONS_DISABLEALL     40179
#define ID_NOTIFICATIONS_NEWPROCESSES   40180
#define ID_NOTIFICATIONS_TERMINATEDPROCESSES 40181
#define ID_NOTIFICATIONS_NEWSERVICES    40182
#define ID_NOTIFICATIONS_STARTEDSERVICES 40183
#define ID_NOTIFICATIONS_STOPPEDSERVICES 40184
#define ID_NOTIFICATIONS_DELETEDSERVICES 40185
#define ID_NOTIFICATIONS_MODIFIEDSERVICES 40186
#define ID_MISCELLANEOUS_GDIHANDLES     40188
#define ID_MISCELLANEOUS_HEAPS          40189
#define ID_ESC_EXIT                     40190
#define ID_PROCESS_COPY                 40194
#define ID_THREAD_COPY                  40195
#define ID_NETWORK_COPY                 40197
#define ID_SERVICE_COPY                 40198
#define ID_MODULE_COPY                  40199
#define ID_HANDLE_COPY                  40200
#define ID_OBJECT_COPY                  40201
#define ID_MEMORY_SAVE                  40208
#define ID_MEMORY_CHANGEPROTECTION      40209
#define ID_MEMORY_FREE                  40210
#define ID_MEMORY_DECOMMIT              40211
#define ID_MEMORY_COPY                  40213
#define ID_MEMORY_READWRITEMEMORY       40214
#define ID_FILTER_CONTAINS              40216
#define ID_FILTER_CONTAINS_CASEINSENSITIVE 40218
#define ID_FILTER_REGEX                 40219
#define ID_FILTER_REGEX_CASEINSENSITIVE 40221
#define ID_TAB_NEXT                     40223
#define ID_TAB_PREV                     40224
#define ID_MISCELLANEOUS_RUNAS          40229
#define ID_MISCELLANEOUS_RUNASTHISUSER  40230
#define ID_VIEW_HIDEPROCESSESFROMOTHERUSERS 40232
#define ID_THREAD_AFFINITY              40233
#define ID_THREAD_BOOST                 40234
#define ID_VIEW_HIDESIGNEDPROCESSES     40234
#define ID_VIEW_UPDATEAUTOMATICALLY     40235
#define ID_HACKER_RUNASLIMITEDUSER      40236
#define ID_USER_REMOTECONTROL           40237
#define ID_PAGEPRIORITY_NORMAL          40239
#define ID_PAGEPRIORITY_BELOWNORMAL     40240
#define ID_PAGEPRIORITY_MEDIUM          40241
#define ID_PAGEPRIORITY_LOW             40242
#define ID_PAGEPRIORITY_VERYLOW         40243
#define ID_VIEW_SHOWCPUBELOW001         40246
#define ID_MODULE_OPENFILELOCATION      40247
#define ID_PROCESS_OPENFILELOCATION     40248
#define ID_MISCELLANEOUS_REDUCEWORKINGSET 40249
#define ID_EMPTY_EMPTYWORKINGSETS       40250
#define ID_EMPTY_EMPTYMODIFIEDPAGELIST  40251
#define ID_EMPTY_EMPTYSTANDBYLIST       40252
#define ID_EMPTY_EMPTYPRIORITY0STANDBYLIST 40253
#define IDC_BACK                        40255
#define ID_VIEW_ORGANIZECOLUMNSETS      40256
#define ID_VIEW_SAVECOLUMNSET           40257
#define ID_VIEW_LOADCOLUMNSET           40258
#define ID_DIGIT1                       40263
#define ID_DIGIT2                       40264
#define ID_DIGIT3                       40265
#define ID_DIGIT4                       40266
#define ID_DIGIT5                       40267
#define ID_DIGIT6                       40268
#define ID_DIGIT7                       40269
#define ID_DIGIT8                       40270
#define ID_DIGIT9                       40271
#define ID_VIEW_HIDEWAITINGCONNECTIONS  40272
#define ID_VIEW_HIDEDRIVERSERVICES      40273
#define ID_VIEW_HIDEMICROSOFTSERVICES   40274
#define ID_VIEW_SECTIONPLACEHOLDER      40274
#define ID_VIEW_SCROLLTONEWPROCESSES    40275
#define ID_TOOLS_STARTTASKMANAGER       40277
#define ID_COMPUTER_SHUTDOWNHYBRID      40278
#define ID_COMPUTER_RESTARTADVOPTIONS   40279
#define ID_COMPUTER_RESTARTBOOTOPTIONS  40280
#define ID_COMPUTER_RESTARTFWOPTIONS    40281
#define ID_COMPUTER_RESTARTFWDEVICE     40282
#define ID_HANDLE_OBJECTPROPERTIES1     40282
#define ID_COMPUTER_RESTARTBOOTDEVICE   40283
#define ID_HANDLE_OBJECTPROPERTIES2     40283
#define ID_OBJECT_GOTOOWNINGPROCESS     40284
#define ID_NETWORK_GOTOSERVICE          40285
#define ID_SERVICE_OPENFILELOCATION     40286
#define ID_PROCESS_GOTOPROCESS          40287
#define ID_MINIINFO_REFRESH             40288
#define ID_MINIINFO_REFRESHAUTOMATICALLY 40289
#define ID_TOOLS_STARTRESOURCEMONITOR   40290
#define IDC_MAXSCREEN                   40293
#define ID_EMPTY_COMPRESSIONSTORE       40294
#define ID_EMPTY_COMBINEMEMORYLISTS     40295
#define ID_PRIVILEGE_RESET              40296
#define ID_GROUP_ENABLE                 40297
#define ID_THREAD_CRITICAL              40297
#define ID_GROUP_DISABLE                40298
#define ID_GROUP_RESET                  40299
#define ID_TOOLS_SCM_PERMISSIONS        40300
#define ID_TOOLS_RDP_PERMISSIONS        40301
#define ID_TOOLS_PWR_PERMISSIONS        40302
#define ID_TOOLS_WMI_PERMISSIONS        40303
#define ID_UIACCESS_REMOVE              40304
#define ID_TOOLS_LIVEDUMP               40305
#define IDDYNAMIC                       50000
#define IDPLUGINS                       55000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        262
#define _APS_NEXT_COMMAND_VALUE         40298
#define _APS_NEXT_CONTROL_VALUE         1413
#define _APS_NEXT_SYMED_VALUE           170
#endif
#endif
