/*
 * Copyright (c) 2022 Winsider Seminars & Solutions, Inc.  All rights reserved.
 *
 * This file is part of System Informer.
 *
 * Authors:
 *
 *     wj32    2008-2016
 *     dmex    2017-2024
 *
 *
 * This file was automatically generated.
 *
 * Do not link at runtime. Use the SystemInformer.def.h header file instead.
 *
 */

#pragma once

#ifndef _PH_EXPORT_DEF_H
#define _PH_EXPORT_DEF_H

#define EXPORT_PHADDPROCESSPROPPAGE                                    1001
#define EXPORT_PHADDPROCESSPROPPAGE2                                   1002
#define EXPORT_PHADDPROPPAGELAYOUTITEM                                 1003
#define EXPORT_PHADDTREENEWFILTER                                      1004
#define EXPORT_PHAPPLYTREENEWFILTERS                                   1005
#define EXPORT_PHAPPLYTREENEWFILTERSTONODE                             1006
#define EXPORT_PHCHOICEDIALOG                                          1007
#define EXPORT_PHCMLOADSETTINGS                                        1008
#define EXPORT_PHCMSAVESETTINGS                                        1009
#define EXPORT_PHCOPYLISTVIEW                                          1010
#define EXPORT_PHCOPYLISTVIEWINFOTIP                                   1011
#define EXPORT_PHCREATEKSISETTINGSBLOB                                 1012
#define EXPORT_PHCREATEPROCESSPROPCONTEXT                              1013
#define EXPORT_PHCREATEPROCESSPROPPAGECONTEXT                          1014
#define EXPORT_PHCREATEPROCESSPROPPAGECONTEXTEX                        1015
#define EXPORT_PHCREATESEARCHCONTROL                                   1016
#define EXPORT_PHCREATESERVICELISTCONTROL                              1017
#define EXPORT_PHDELETEMEMORYITEMLIST                                  1018
#define EXPORT_PHDELETESTATICWINDOWICON                                1019
#define EXPORT_PHDELETETREENEWCOLUMNMENU                               1020
#define EXPORT_PHDELETETREENEWFILTERSUPPORT                            1021
#define EXPORT_PHDEREFERENCEPROCESSRECORD                              1022
#define EXPORT_PHDESELECTALLPROCESSNODES                               1023
#define EXPORT_PHDESELECTALLSERVICENODES                               1024
#define EXPORT_PHDESTROYWINDOWICON                                     1025
#define EXPORT_PHDEVICEPROVIDERINITIALIZATION                          1026
#define EXPORT_PHDOPROPPAGELAYOUT                                      1027
#define EXPORT_PHDUPLICATEPROCESSINFORMATION                           1028
#define EXPORT_PHDUPLICATEPROCESSNODELIST                              1029
#define EXPORT_PHENUMNETWORKITEMS                                      1030
#define EXPORT_PHENUMNETWORKITEMSBYPROCESSID                           1031
#define EXPORT_PHENUMPROCESSITEMS                                      1032
#define EXPORT_PHEXECUTERUNASCOMMAND2                                  1033
#define EXPORT_PHEXECUTERUNASCOMMAND3                                  1034
#define EXPORT_PHEXPANDALLPROCESSNODES                                 1035
#define EXPORT_PHFINDNETWORKNODE                                       1036
#define EXPORT_PHFINDPROCESSNODE                                       1037
#define EXPORT_PHFINDPROCESSRECORD                                     1038
#define EXPORT_PHFINDSERVICENODE                                       1039
#define EXPORT_PHFORMATLOGENTRY                                        1040
#define EXPORT_PHGETAPPLICATIONICON                                    1041
#define EXPORT_PHGETAPPLICATIONICONEX                                  1042
#define EXPORT_PHGETCLIENTIDNAME                                       1043
#define EXPORT_PHGETCLIENTIDNAMEEX                                     1044
#define EXPORT_PHGETDEVICEICON                                         1045
#define EXPORT_PHGETDEVICEPROPERTY                                     1046
#define EXPORT_PHGETFILTERSUPPORTNETWORKTREELIST                       1047
#define EXPORT_PHGETFILTERSUPPORTPROCESSTREELIST                       1048
#define EXPORT_PHGETFILTERSUPPORTSERVICETREELIST                       1049
#define EXPORT_PHGETGENERALCALLBACK                                    1050
#define EXPORT_PHGETIMAGELISTICON                                      1051
#define EXPORT_PHGETLISTVIEWCONTEXTMENUPOINT                           1052
#define EXPORT_PHGETPHRELEASECHANNEL                                   1053
#define EXPORT_PHGETPHRELEASECHANNELSTRING                             1054
#define EXPORT_PHGETPHVERSION                                          1055
#define EXPORT_PHGETPHVERSIONHASH                                      1056
#define EXPORT_PHGETPHVERSIONNUMBERS                                   1057
#define EXPORT_PHGETPROCESSISSUSPENDED                                 1058
#define EXPORT_PHGETPROCESSKNOWNTYPE                                   1059
#define EXPORT_PHGETPROCESSKNOWNTYPEEX                                 1060
#define EXPORT_PHGETPROCESSPRIORITYCLASSSTRING                         1061
#define EXPORT_PHGETPROCESSSMALLIMAGELIST                              1062
#define EXPORT_PHGETPROTOCOLTYPENAME                                   1063
#define EXPORT_PHGETSELECTEDANDPROPAGATEPROCESSITEMS                   1064
#define EXPORT_PHGETSELECTEDPROCESSITEM                                1065
#define EXPORT_PHGETSELECTEDPROCESSITEMS                               1066
#define EXPORT_PHGETSELECTEDPROCESSNODES                               1067
#define EXPORT_PHGETSELECTEDSERVICEITEM                                1068
#define EXPORT_PHGETSELECTEDSERVICEITEMS                               1069
#define EXPORT_PHGETSERVICECHANGE                                      1070
#define EXPORT_PHGETSHIELDBITMAP                                       1071
#define EXPORT_PHGETSTATISTICSTIME                                     1072
#define EXPORT_PHGETSTATISTICSTIMESTRING                               1073
#define EXPORT_PHGETTCPSTATENAME                                       1074
#define EXPORT_PHHANDLECOPYCELLEMENUITEM                               1075
#define EXPORT_PHHANDLECOPYLISTVIEWEMENUITEM                           1076
#define EXPORT_PHHANDLELISTVIEWNOTIFYBEHAVIORS                         1077
#define EXPORT_PHHANDLELISTVIEWNOTIFYFORCOPY                           1078
#define EXPORT_PHHANDLETREENEWCOLUMNMENU                               1079
#define EXPORT_PHIMAGELISTEXTRACTICON                                  1080
#define EXPORT_PHIMAGELISTFLUSHCACHE                                   1081
#define EXPORT_PHINITIALIZETREENEWCOLUMNMENU                           1082
#define EXPORT_PHINITIALIZETREENEWCOLUMNMENUEX                         1083
#define EXPORT_PHINITIALIZETREENEWFILTERSUPPORT                        1084
#define EXPORT_PHINSERTCOPYCELLEMENUITEM                               1085
#define EXPORT_PHINSERTCOPYLISTVIEWEMENUITEM                           1086
#define EXPORT_PHINSERTHANDLEOBJECTPROPERTIESEMENUITEMS                1087
#define EXPORT_PHINVALIDATEALLPROCESSNODES                             1088
#define EXPORT_PHISPROCESSSUSPENDED                                    1089
#define EXPORT_PHLOADSYMBOLPROVIDEROPTIONS                             1090
#define EXPORT_PHLOGMESSAGEENTRY                                       1091
#define EXPORT_PHLOOKUPDEVICEITEM                                      1092
#define EXPORT_PHLOOKUPDEVICEITEMBYHASH                                1093
#define EXPORT_PHLOOKUPDEVICEPROPERTYCLASS                             1094
#define EXPORT_PHLOOKUPMEMORYITEMLIST                                  1095
#define EXPORT_PHPROCESSIMAGELISTINITIALIZATION                        1096
#define EXPORT_PHPROPPAGEDLGPROCHEADER                                 1097
#define EXPORT_PHQUERYMEMORYITEMLIST                                   1098
#define EXPORT_PHREFERENCEDEVICEITEM                                   1099
#define EXPORT_PHREFERENCEDEVICEITEM2                                  1100
#define EXPORT_PHREFERENCEDEVICEITEMBYHASH                             1101
#define EXPORT_PHREFERENCEDEVICETREE                                   1102
#define EXPORT_PHREFERENCEDEVICETREEEX                                 1103
#define EXPORT_PHREFERENCENETWORKITEM                                  1104
#define EXPORT_PHREFERENCEPROCESSITEM                                  1105
#define EXPORT_PHREFERENCEPROCESSITEMFORPARENT                         1106
#define EXPORT_PHREFERENCEPROCESSITEMFORRECORD                         1107
#define EXPORT_PHREFERENCEPROCESSRECORD                                1108
#define EXPORT_PHREFERENCEPROCESSRECORDFORSTATISTICS                   1109
#define EXPORT_PHREFERENCEPROCESSRECORDSAFE                            1110
#define EXPORT_PHREFERENCESERVICEITEM                                  1111
#define EXPORT_PHREGISTERDIALOG                                        1112
#define EXPORT_PHREGISTERMESSAGELOOPFILTER                             1113
#define EXPORT_PHREMOVETREENEWFILTER                                   1114
#define EXPORT_PHSEARCHCONTROLMATCH                                    1115
#define EXPORT_PHSEARCHCONTROLMATCHLONGHINTZ                           1116
#define EXPORT_PHSEARCHCONTROLMATCHPOINTER                             1117
#define EXPORT_PHSEARCHCONTROLMATCHPOINTERRANGE                        1118
#define EXPORT_PHSEARCHCONTROLMATCHZ                                   1119
#define EXPORT_PHSEARCHONLINESTRING                                    1120
#define EXPORT_PHSELECTANDENSUREVISIBLEPROCESSNODE                     1121
#define EXPORT_PHSELECTANDENSUREVISIBLESERVICENODE                     1122
#define EXPORT_PHSETAPPLICATIONWINDOWICON                              1123
#define EXPORT_PHSETAPPLICATIONWINDOWICONEX                            1124
#define EXPORT_PHSETPROCESSITEMAFFINITYMASK                            1125
#define EXPORT_PHSETPROCESSITEMIOPRIORITY                              1126
#define EXPORT_PHSETPROCESSITEMPAGEPRIORITY                            1127
#define EXPORT_PHSETPROCESSITEMPRIORITY                                1128
#define EXPORT_PHSETPROCESSITEMPRIORITYBOOST                           1129
#define EXPORT_PHSETPROCESSITEMTHROTTLINGSTATE                         1130
#define EXPORT_PHSETSELECTTHREADIDPROCESSPROPCONTEXT                   1131
#define EXPORT_PHSETSTATICWINDOWICON                                   1132
#define EXPORT_PHSETWINDOWICON                                         1133
#define EXPORT_PHSHELLEXECUTEUSERSTRING                                1134
#define EXPORT_PHSHELLOPENKEY                                          1135
#define EXPORT_PHSHELLOPENKEY2                                         1136
#define EXPORT_PHSHELLPROCESSHACKER                                    1137
#define EXPORT_PHSHOWCHOOSEPROCESSDIALOG                               1138
#define EXPORT_PHSHOWHANDLEOBJECTPROPERTIES1                           1139
#define EXPORT_PHSHOWHANDLEOBJECTPROPERTIES2                           1140
#define EXPORT_PHSHOWICONNOTIFICATION                                  1141
#define EXPORT_PHSHOWPROCESSAFFINITYDIALOG2                            1142
#define EXPORT_PHSHOWPROCESSPROPERTIES                                 1143
#define EXPORT_PHSHOWPROCESSRECORDDIALOG                               1144
#define EXPORT_PHSHOWSYSTEMINFORMATIONDIALOG                           1145
#define EXPORT_PHSHOWTHREADAFFINITYDIALOG                              1146
#define EXPORT_PHSIDOUBLELABELYFUNCTION                                1147
#define EXPORT_PHSISETCOLORSGRAPHDRAWINFO                              1148
#define EXPORT_PHSISIZELABELYFUNCTION                                  1149
#define EXPORT_PHSIUINT64LABELYFUNCTION                                1150
#define EXPORT_PHUNREGISTERDIALOG                                      1151
#define EXPORT_PHUNREGISTERMESSAGELOOPFILTER                           1152
#define EXPORT_PHUPDATEPROCESSNODE                                     1153
#define EXPORT_PHUPDATESERVICENODE                                     1154
#define EXPORT_PHWORDMATCHSTRINGREF                                    1155
#define EXPORT_PHWRITEPHTEXTHEADER                                     1156
#define EXPORT_PHACHOICEDIALOG                                         1157
#define EXPORT_PHAGETPROCESSKNOWNCOMMANDLINE                           1158
#define EXPORT_PHENUMERATEPLUGINS                                      1159
#define EXPORT_PHFINDPLUGIN2                                           1160
#define EXPORT_PHGETPLUGINCALLBACK                                     1161
#define EXPORT_PHGETPLUGINFILENAME                                     1162
#define EXPORT_PHGETPLUGININFORMATION                                  1163
#define EXPORT_PHGETPLUGININTERFACE                                    1164
#define EXPORT_PHGETPLUGINNAME                                         1165
#define EXPORT_PHPLUGINADDMENUHOOK                                     1166
#define EXPORT_PHPLUGINADDTREENEWCOLUMN                                1167
#define EXPORT_PHPLUGINCALLPHSVC                                       1168
#define EXPORT_PHPLUGINCREATEEMENUITEM                                 1169
#define EXPORT_PHPLUGINCREATETABPAGE                                   1170
#define EXPORT_PHPLUGINENABLETREENEWNOTIFY                             1171
#define EXPORT_PHPLUGINGETOBJECTEXTENSION                              1172
#define EXPORT_PHPLUGINGETSYSTEMSTATISTICS                             1173
#define EXPORT_PHPLUGININVOKEWINDOWCALLBACK                            1174
#define EXPORT_PHPLUGINQUERYPHSVC                                      1175
#define EXPORT_PHPLUGINRESERVEIDS                                      1176
#define EXPORT_PHPLUGINSETOBJECTEXTENSION                              1177
#define EXPORT_PHREGISTERPLUGIN                                        1178
#define EXPORT_PHSVCCALLCHANGESERVICECONFIG                            1179
#define EXPORT_PHSVCCALLCHANGESERVICECONFIG2                           1180
#define EXPORT_PHSVCCALLPOSTMESSAGE                                    1181
#define EXPORT_PHSVCCALLSENDMESSAGE                                    1182
#define EXPORT_PHUICLOSECONNECTIONS                                    1183
#define EXPORT_PHUICLOSEHANDLES                                        1184
#define EXPORT_PHUICONNECTSESSION                                      1185
#define EXPORT_PHUICONNECTTOPHSVC                                      1186
#define EXPORT_PHUICONNECTTOPHSVCEX                                    1187
#define EXPORT_PHUICONTINUESERVICE                                     1188
#define EXPORT_PHUICONTINUESERVICES                                    1189
#define EXPORT_PHUIDEBUGPROCESS                                        1190
#define EXPORT_PHUIDELETESERVICE                                       1191
#define EXPORT_PHUIDETACHFROMDEBUGGERPROCESS                           1192
#define EXPORT_PHUIDISCONNECTFROMPHSVC                                 1193
#define EXPORT_PHUIDISCONNECTSESSION                                   1194
#define EXPORT_PHUIFLUSHHEAPPROCESSES                                  1195
#define EXPORT_PHUIFREEMEMORY                                          1196
#define EXPORT_PHUIFREEZETREEPROCESS                                   1197
#define EXPORT_PHUIHIBERNATECOMPUTER                                   1198
#define EXPORT_PHUILOADDLLPROCESS                                      1199
#define EXPORT_PHUILOCKCOMPUTER                                        1200
#define EXPORT_PHUILOGOFFCOMPUTER                                      1201
#define EXPORT_PHUILOGOFFSESSION                                       1202
#define EXPORT_PHUIPAUSESERVICE                                        1203
#define EXPORT_PHUIPAUSESERVICES                                       1204
#define EXPORT_PHUIREDUCEWORKINGSETPROCESSES                           1205
#define EXPORT_PHUIRESTARTCOMPUTER                                     1206
#define EXPORT_PHUIRESTARTPROCESS                                      1207
#define EXPORT_PHUIRESUMEPROCESSES                                     1208
#define EXPORT_PHUIRESUMETHREADS                                       1209
#define EXPORT_PHUIRESUMETREEPROCESS                                   1210
#define EXPORT_PHUISETATTRIBUTESHANDLE                                 1211
#define EXPORT_PHUISETBOOSTPRIORITYPROCESS                             1212
#define EXPORT_PHUISETBOOSTPRIORITYPROCESSES                           1213
#define EXPORT_PHUISETBOOSTPRIORITYTHREAD                              1214
#define EXPORT_PHUISETBOOSTPRIORITYTHREADS                             1215
#define EXPORT_PHUISETCRITICALPROCESS                                  1216
#define EXPORT_PHUISETECOMODEPROCESS                                   1217
#define EXPORT_PHUISETEXECUTIONREQUIREDPROCESS                         1218
#define EXPORT_PHUISETIOPRIORITYPROCESSES                              1219
#define EXPORT_PHUISETIOPRIORITYTHREAD                                 1220
#define EXPORT_PHUISETPAGEPRIORITYPROCESS                              1221
#define EXPORT_PHUISETPAGEPRIORITYTHREAD                               1222
#define EXPORT_PHUISETPRIORITYPROCESSES                                1223
#define EXPORT_PHUISETPRIORITYTHREAD                                   1224
#define EXPORT_PHUISETPRIORITYTHREADS                                  1225
#define EXPORT_PHUISETVIRTUALIZATIONPROCESS                            1226
#define EXPORT_PHUISHUTDOWNCOMPUTER                                    1227
#define EXPORT_PHUISLEEPCOMPUTER                                       1228
#define EXPORT_PHUISTARTSERVICE                                        1229
#define EXPORT_PHUISTARTSERVICES                                       1230
#define EXPORT_PHUISTOPSERVICE                                         1231
#define EXPORT_PHUISTOPSERVICES                                        1232
#define EXPORT_PHUISUSPENDPROCESSES                                    1233
#define EXPORT_PHUISUSPENDTHREADS                                      1234
#define EXPORT_PHUISUSPENDTREEPROCESS                                  1235
#define EXPORT_PHUITERMINATEPROCESSES                                  1236
#define EXPORT_PHUITERMINATETHREADS                                    1237
#define EXPORT_PHUITERMINATETREEPROCESS                                1238
#define EXPORT_PHUITHAWTREEPROCESS                                     1239
#define EXPORT_PHUIUNLOADMODULE                                        1240
#define EXPORT_PHAUTODEREFERENCEOBJECT                                 1241
#define EXPORT_PHCREATEALLOC                                           1242
#define EXPORT_PHCREATEOBJECT                                          1243
#define EXPORT_PHCREATEOBJECTTYPE                                      1244
#define EXPORT_PHCREATEOBJECTTYPEEX                                    1245
#define EXPORT_PHDELETEAUTOPOOL                                        1246
#define EXPORT_PHDEREFERENCEOBJECT                                     1247
#define EXPORT_PHDEREFERENCEOBJECTDEFERDELETE                          1248
#define EXPORT_PHDEREFERENCEOBJECTEX                                   1249
#define EXPORT_PHDRAINAUTOPOOL                                         1250
#define EXPORT_PHGETOBJECTTYPE                                         1251
#define EXPORT_PHGETOBJECTTYPEINFORMATION                              1252
#define EXPORT_PHINITIALIZEAUTOPOOL                                    1253
#define EXPORT_PHREFERENCEOBJECT                                       1254
#define EXPORT_PHREFERENCEOBJECTEX                                     1255
#define EXPORT_PHREFERENCEOBJECTSAFE                                   1256
#define EXPORT_PHFACQUIREQUEUEDLOCKEXCLUSIVE                           1257
#define EXPORT_PHFACQUIREQUEUEDLOCKSHARED                              1258
#define EXPORT_PHFPULSEALLCONDITION                                    1259
#define EXPORT_PHFPULSECONDITION                                       1260
#define EXPORT_PHFQUEUEWAKEEVENT                                       1261
#define EXPORT_PHFRELEASEQUEUEDLOCKEXCLUSIVE                           1262
#define EXPORT_PHFRELEASEQUEUEDLOCKSHARED                              1263
#define EXPORT_PHFSETWAKEEVENT                                         1264
#define EXPORT_PHFWAITFORCONDITION                                     1265
#define EXPORT_PHFWAITFORCONDITIONEX                                   1266
#define EXPORT_PHFWAITFORWAKEEVENT                                     1267
#define EXPORT_PHFWAKEFORRELEASEQUEUEDLOCK                             1268
#define EXPORT_PHISEXECUTINGINWOW64                                    1269
#define EXPORT_PHSYSTEMBASICINFORMATION                                1270
#define EXPORT_PHADDELEMENTAVLTREE                                     1271
#define EXPORT_PHADDENTRYHASHTABLE                                     1272
#define EXPORT_PHADDENTRYHASHTABLEEX                                   1273
#define EXPORT_PHADDITEMARRAY                                          1274
#define EXPORT_PHADDITEMLIST                                           1275
#define EXPORT_PHADDITEMPOINTERLIST                                    1276
#define EXPORT_PHADDITEMSIMPLEHASHTABLE                                1277
#define EXPORT_PHADDITEMSARRAY                                         1278
#define EXPORT_PHADDITEMSLIST                                          1279
#define EXPORT_PHADDPLUSMAXMEMORYSINGLES                               1280
#define EXPORT_PHALLOCATE                                              1281
#define EXPORT_PHALLOCATEEXSAFE                                        1282
#define EXPORT_PHALLOCATEFROMFREELIST                                  1283
#define EXPORT_PHALLOCATEPAGE                                          1284
#define EXPORT_PHALLOCATESAFE                                          1285
#define EXPORT_PHAPPENDBYTESBUILDER                                    1286
#define EXPORT_PHAPPENDBYTESBUILDER2                                   1287
#define EXPORT_PHAPPENDBYTESBUILDEREX                                  1288
#define EXPORT_PHAPPENDCHARSTRINGBUILDER                               1289
#define EXPORT_PHAPPENDCHARSTRINGBUILDER2                              1290
#define EXPORT_PHAPPENDFORMATSTRINGBUILDER                             1291
#define EXPORT_PHAPPENDFORMATSTRINGBUILDER_V                           1292
#define EXPORT_PHAPPENDSTRINGBUILDEREX                                 1293
#define EXPORT_PHBUFFERTOHEXSTRING                                     1294
#define EXPORT_PHBUFFERTOHEXSTRINGEX                                   1295
#define EXPORT_PHCLEARARRAY                                            1296
#define EXPORT_PHCLEARHASHTABLE                                        1297
#define EXPORT_PHCLEARLIST                                             1298
#define EXPORT_PHCOMPARESTRINGREF                                      1299
#define EXPORT_PHCOMPARESTRINGZNATURAL                                 1300
#define EXPORT_PHCONCATSTRINGREF2                                      1301
#define EXPORT_PHCONCATSTRINGREF3                                      1302
#define EXPORT_PHCONCATSTRINGREF4                                      1303
#define EXPORT_PHCONCATSTRINGS                                         1304
#define EXPORT_PHCONCATSTRINGS2                                        1305
#define EXPORT_PHCONCATSTRINGS_V                                       1306
#define EXPORT_PHCONVERTMULTIBYTETOUTF16                               1307
#define EXPORT_PHCONVERTMULTIBYTETOUTF16EX                             1308
#define EXPORT_PHCONVERTUTF16TOASCIIEX                                 1309
#define EXPORT_PHCONVERTUTF16TOMULTIBYTE                               1310
#define EXPORT_PHCONVERTUTF16TOMULTIBYTEEX                             1311
#define EXPORT_PHCONVERTUTF16TOUTF8                                    1312
#define EXPORT_PHCONVERTUTF16TOUTF8BUFFER                              1313
#define EXPORT_PHCONVERTUTF16TOUTF8EX                                  1314
#define EXPORT_PHCONVERTUTF16TOUTF8SIZE                                1315
#define EXPORT_PHCONVERTUTF8TOUTF16                                    1316
#define EXPORT_PHCONVERTUTF8TOUTF16BUFFER                              1317
#define EXPORT_PHCONVERTUTF8TOUTF16EX                                  1318
#define EXPORT_PHCONVERTUTF8TOUTF16SIZE                                1319
#define EXPORT_PHCOPYBYTESZ                                            1320
#define EXPORT_PHCOPYCONVERTCIRCULARBUFFERULONG                        1321
#define EXPORT_PHCOPYSTRINGZ                                           1322
#define EXPORT_PHCOPYSTRINGZFROMBYTES                                  1323
#define EXPORT_PHCOPYSTRINGZFROMMULTIBYTE                              1324
#define EXPORT_PHCOUNTSTRINGZ                                          1325
#define EXPORT_PHCREATEBYTES                                           1326
#define EXPORT_PHCREATEBYTESEX                                         1327
#define EXPORT_PHCREATEHASHTABLE                                       1328
#define EXPORT_PHCREATELIST                                            1329
#define EXPORT_PHCREATEPOINTERLIST                                     1330
#define EXPORT_PHCREATESIMPLEHASHTABLE                                 1331
#define EXPORT_PHCREATESTRING3                                         1332
#define EXPORT_PHCREATESTRINGEX                                        1333
#define EXPORT_PHCREATETHREAD                                          1334
#define EXPORT_PHCREATETHREAD2                                         1335
#define EXPORT_PHCREATETHREADEX                                        1336
#define EXPORT_PHDECODEUNICODEDECODER                                  1337
#define EXPORT_PHDELAYEXECUTION                                        1338
#define EXPORT_PHDELETEARRAY                                           1339
#define EXPORT_PHDELETEBYTESBUILDER                                    1340
#define EXPORT_PHDELETECALLBACK                                        1341
#define EXPORT_PHDELETEFREELIST                                        1342
#define EXPORT_PHDELETESTRINGBUILDER                                   1343
#define EXPORT_PHDIVIDESINGLESBYSINGLE                                 1344
#define EXPORT_PHDOSERRORTONTSTATUS                                    1345
#define EXPORT_PHDUPLICATEBYTESZ                                       1346
#define EXPORT_PHDUPLICATEBYTESZSAFE                                   1347
#define EXPORT_PHDUPLICATESTRINGZ                                      1348
#define EXPORT_PHENCODEUNICODE                                         1349
#define EXPORT_PHENUMAVLTREE                                           1350
#define EXPORT_PHENUMHASHTABLE                                         1351
#define EXPORT_PHENUMPOINTERLISTEX                                     1352
#define EXPORT_PHEQUALSTRINGREF                                        1353
#define EXPORT_PHEXPONENTIATE                                          1354
#define EXPORT_PHEXPONENTIATE64                                        1355
#define EXPORT_PHEXTRACTICON                                           1356
#define EXPORT_PHEXTRACTICONEX                                         1357
#define EXPORT_PHFILLMEMORYULONG                                       1358
#define EXPORT_PHFINALBYTESBUILDERBYTES                                1359
#define EXPORT_PHFINALSTRINGBUILDERSTRING                              1360
#define EXPORT_PHFINDCHARINSTRINGREF                                   1361
#define EXPORT_PHFINDELEMENTAVLTREE                                    1362
#define EXPORT_PHFINDENTRYHASHTABLE                                    1363
#define EXPORT_PHFINDITEMLIST                                          1364
#define EXPORT_PHFINDITEMPOINTERLIST                                   1365
#define EXPORT_PHFINDITEMSIMPLEHASHTABLE                               1366
#define EXPORT_PHFINDLASTCHARINSTRINGREF                               1367
#define EXPORT_PHFINDSTRINGINSTRINGREF                                 1368
#define EXPORT_PHFORMAT                                                1369
#define EXPORT_PHFORMATBYTES                                           1370
#define EXPORT_PHFORMATBYTES_V                                         1371
#define EXPORT_PHFORMATSTRING                                          1372
#define EXPORT_PHFORMATSTRING_V                                        1373
#define EXPORT_PHFORMATTOBUFFER                                        1374
#define EXPORT_PHFREE                                                  1375
#define EXPORT_PHFREEPAGE                                              1376
#define EXPORT_PHFREETOFREELIST                                        1377
#define EXPORT_PHGETLASTERROR                                          1378
#define EXPORT_PHGETPRIMENUMBER                                        1379
#define EXPORT_PHHASHBYTES                                             1380
#define EXPORT_PHHASHSTRINGREF                                         1381
#define EXPORT_PHHASHSTRINGREFEX                                       1382
#define EXPORT_PHHEXSTRINGTOBUFFER                                     1383
#define EXPORT_PHHEXSTRINGTOBUFFEREX                                   1384
#define EXPORT_PHHUNGWINDOWFROMGHOSTWINDOW                             1385
#define EXPORT_PHINITIALIZEARRAY                                       1386
#define EXPORT_PHINITIALIZEAVLTREE                                     1387
#define EXPORT_PHINITIALIZEBYTESBUILDER                                1388
#define EXPORT_PHINITIALIZECALLBACK                                    1389
#define EXPORT_PHINITIALIZEFREELIST                                    1390
#define EXPORT_PHINITIALIZESTRINGBUILDER                               1391
#define EXPORT_PHINSERTITEMLIST                                        1392
#define EXPORT_PHINSERTITEMSLIST                                       1393
#define EXPORT_PHINSERTSTRINGBUILDER                                   1394
#define EXPORT_PHINSERTSTRINGBUILDER2                                  1395
#define EXPORT_PHINSERTSTRINGBUILDEREX                                 1396
#define EXPORT_PHINTEGERTOSTRING64                                     1397
#define EXPORT_PHINVOKECALLBACK                                        1398
#define EXPORT_PHLOADINDIRECTSTRING                                    1399
#define EXPORT_PHLOADRESOURCE                                          1400
#define EXPORT_PHLOCALTIMETOSYSTEMTIME                                 1401
#define EXPORT_PHLOWERBOUNDELEMENTAVLTREE                              1402
#define EXPORT_PHLOWERDUALBOUNDELEMENTAVLTREE                          1403
#define EXPORT_PHMAXMEMORYSINGLES                                      1404
#define EXPORT_PHMAXIMUMELEMENTAVLTREE                                 1405
#define EXPORT_PHMINIMUMELEMENTAVLTREE                                 1406
#define EXPORT_PHNTSTATUSFILENOTFOUND                                  1407
#define EXPORT_PHNTSTATUSTODOSERROR                                    1408
#define EXPORT_PHPREDECESSORELEMENTAVLTREE                             1409
#define EXPORT_PHPRINTTIMESPAN                                         1410
#define EXPORT_PHQUERYPERFORMANCECOUNTER                               1411
#define EXPORT_PHQUERYPERFORMANCEFREQUENCY                             1412
#define EXPORT_PHQUERYSYSTEMTIME                                       1413
#define EXPORT_PHQUERYTIMEZONEBIAS                                     1414
#define EXPORT_PHREALLOCATE                                            1415
#define EXPORT_PHREALLOCATESAFE                                        1416
#define EXPORT_PHREADTIMESTAMPCOUNTER                                  1417
#define EXPORT_PHREFERENCEEMPTYSTRING                                  1418
#define EXPORT_PHREGISTERCALLBACK                                      1419
#define EXPORT_PHREGISTERCALLBACKEX                                    1420
#define EXPORT_PHREMOVEELEMENTAVLTREE                                  1421
#define EXPORT_PHREMOVEENTRYHASHTABLE                                  1422
#define EXPORT_PHREMOVEITEMARRAY                                       1423
#define EXPORT_PHREMOVEITEMLIST                                        1424
#define EXPORT_PHREMOVEITEMPOINTERLIST                                 1425
#define EXPORT_PHREMOVEITEMSIMPLEHASHTABLE                             1426
#define EXPORT_PHREMOVEITEMSARRAY                                      1427
#define EXPORT_PHREMOVEITEMSLIST                                       1428
#define EXPORT_PHREMOVESTRINGBUILDER                                   1429
#define EXPORT_PHRESIZEARRAY                                           1430
#define EXPORT_PHRESIZELIST                                            1431
#define EXPORT_PHROUNDUPTOPOWEROFTWO                                   1432
#define EXPORT_PHSECONDSSINCE1970TOTIME                                1433
#define EXPORT_PHSPLITSTRINGREFATCHAR                                  1434
#define EXPORT_PHSPLITSTRINGREFATLASTCHAR                              1435
#define EXPORT_PHSPLITSTRINGREFATSTRING                                1436
#define EXPORT_PHSPLITSTRINGREFEX                                      1437
#define EXPORT_PHSTRINGTODOUBLE                                        1438
#define EXPORT_PHSTRINGTOINTEGER64                                     1439
#define EXPORT_PHSTRINGTOUINT64                                        1440
#define EXPORT_PHSUCCESSORELEMENTAVLTREE                               1441
#define EXPORT_PHSYSTEMTIMETOLOCALTIME                                 1442
#define EXPORT_PHTIMETOSECONDSSINCE1970                                1443
#define EXPORT_PHTRIMSTRINGREF                                         1444
#define EXPORT_PHUNREGISTERCALLBACK                                    1445
#define EXPORT_PHUPPERBOUNDELEMENTAVLTREE                              1446
#define EXPORT_PHUPPERDUALBOUNDELEMENTAVLTREE                          1447
#define EXPORT_PHWRITEUNICODEDECODER                                   1448
#define EXPORT_PHZEROEXTENDTOUTF16BUFFER                               1449
#define EXPORT_PHZEROEXTENDTOUTF16EX                                   1450
#define EXPORT_PHFACQUIRERUNDOWNPROTECTION                             1451
#define EXPORT_PHFBEGININITONCE                                        1452
#define EXPORT_PHFENDINITONCE                                          1453
#define EXPORT_PHFINITIALIZEBARRIER                                    1454
#define EXPORT_PHFINITIALIZEEVENT                                      1455
#define EXPORT_PHFINITIALIZEINITONCE                                   1456
#define EXPORT_PHFINITIALIZERUNDOWNPROTECTION                          1457
#define EXPORT_PHFRELEASERUNDOWNPROTECTION                             1458
#define EXPORT_PHFRESETEVENT                                           1459
#define EXPORT_PHFSETEVENT                                             1460
#define EXPORT_PHFWAITFORBARRIER                                       1461
#define EXPORT_PHFWAITFOREVENT                                         1462
#define EXPORT_PHFWAITFORRUNDOWNPROTECTION                             1463
#define EXPORT_PHENUMSMBIOS                                            1464
#define EXPORT_PHGETSMBIOSSTRING                                       1465
#define EXPORT_PHADJUSTPRIVILEGE                                       1466
#define EXPORT_PHCONNECTPIPE                                           1467
#define EXPORT_PHCREATEDIRECTORYFULLPATHWIN32                          1468
#define EXPORT_PHCREATEDIRECTORYWIN32                                  1469
#define EXPORT_PHCREATEEVENT                                           1470
#define EXPORT_PHCREATEFILE                                            1471
#define EXPORT_PHCREATEFILEWIN32                                       1472
#define EXPORT_PHCREATEFILEWIN32EX                                     1473
#define EXPORT_PHCREATEKEY                                             1474
#define EXPORT_PHCREATENAMEDPIPE                                       1475
#define EXPORT_PHCREATEPIPE                                            1476
#define EXPORT_PHDELETEDIRECTORYWIN32                                  1477
#define EXPORT_PHDELETEFILE                                            1478
#define EXPORT_PHDELETEFILEWIN32                                       1479
#define EXPORT_PHDELETEVALUEKEY                                        1480
#define EXPORT_PHDESTROYWINDOWREMOTE                                   1481
#define EXPORT_PHDETERMINEDOSPATHNAMETYPE                              1482
#define EXPORT_PHDEVICEIOCONTROLFILE                                   1483
#define EXPORT_PHDISCONNECTNAMEDPIPE                                   1484
#define EXPORT_PHDOESFILEEXIST                                         1485
#define EXPORT_PHDOESFILEEXISTWIN32                                    1486
#define EXPORT_PHDOSPATHNAMETONTPATHNAME                               1487
#define EXPORT_PHENUMBIGPOOLINFORMATION                                1488
#define EXPORT_PHENUMDIRECTORYFILE                                     1489
#define EXPORT_PHENUMDIRECTORYOBJECTS                                  1490
#define EXPORT_PHENUMFILESTREAMS                                       1491
#define EXPORT_PHENUMFIRMWAREENVIRONMENTVALUES                         1492
#define EXPORT_PHENUMGENERICMODULES                                    1493
#define EXPORT_PHENUMHANDLESEX                                         1494
#define EXPORT_PHENUMKERNELMODULES                                     1495
#define EXPORT_PHENUMNEXTPROCESS                                       1496
#define EXPORT_PHENUMNEXTTHREAD                                        1497
#define EXPORT_PHENUMOBJECTIDINFORMATION                               1498
#define EXPORT_PHENUMPAGEFILES                                         1499
#define EXPORT_PHENUMPOOLTAGINFORMATION                                1500
#define EXPORT_PHENUMPROCESSENVIRONMENTVARIABLES                       1501
#define EXPORT_PHENUMPROCESSES                                         1502
#define EXPORT_PHENUMPROCESSESEX                                       1503
#define EXPORT_PHENUMPROCESSHANDLES                                    1504
#define EXPORT_PHENUMREPARSEPOINTINFORMATION                           1505
#define EXPORT_PHENUMERATEKEY                                          1506
#define EXPORT_PHENUMERATEVALUEKEY                                     1507
#define EXPORT_PHFILTERCONNECTCOMMUNICATIONPORT                        1508
#define EXPORT_PHFINDPROCESSINFORMATION                                1509
#define EXPORT_PHFINDPROCESSINFORMATIONBYIMAGENAME                     1510
#define EXPORT_PHGETACTIVEPROCESSORCOUNT                               1511
#define EXPORT_PHGETCONTEXTTHREAD                                      1512
#define EXPORT_PHGETDEVICETYPE                                         1513
#define EXPORT_PHGETDLLHANDLE                                          1514
#define EXPORT_PHGETDRIVERIMAGEFILENAME                                1515
#define EXPORT_PHGETDRIVERNAME                                         1516
#define EXPORT_PHGETDRIVERSERVICEKEYNAME                               1517
#define EXPORT_PHGETFILEFULLATTRIBUTESINFORMATION                      1518
#define EXPORT_PHGETFILENAME                                           1519
#define EXPORT_PHGETFILEPOSITION                                       1520
#define EXPORT_PHGETFILESIZE                                           1521
#define EXPORT_PHGETFIRMWAREENVIRONMENTVARIABLE                        1522
#define EXPORT_PHGETJOBPROCESSIDLIST                                   1523
#define EXPORT_PHGETKERNELFILENAME                                     1524
#define EXPORT_PHGETKERNELFILENAME2                                    1525
#define EXPORT_PHGETKERNELFILENAMEEX                                   1526
#define EXPORT_PHGETMODULEPROCADDRESS                                  1527
#define EXPORT_PHGETNAMEDPIPECLIENTCOMPUTERNAME                        1528
#define EXPORT_PHGETNAMEDPIPECLIENTPROCESSID                           1529
#define EXPORT_PHGETNAMEDPIPESERVERPROCESSID                           1530
#define EXPORT_PHGETOBJECTSECURITY                                     1531
#define EXPORT_PHGETOBJECTTYPEINDEXNAME                                1532
#define EXPORT_PHGETOBJECTTYPENUMBER                                   1533
#define EXPORT_PHGETOWNTOKENATTRIBUTES                                 1534
#define EXPORT_PHGETPNPDEVICENAME                                      1535
#define EXPORT_PHGETPROCEDUREADDRESS                                   1536
#define EXPORT_PHGETPROCEDUREADDRESSREMOTE                             1537
#define EXPORT_PHGETPROCESSCOMMANDLINE                                 1538
#define EXPORT_PHGETPROCESSDEPSTATUS                                   1539
#define EXPORT_PHGETPROCESSDEVICEMAP                                   1540
#define EXPORT_PHGETPROCESSENVIRONMENT                                 1541
#define EXPORT_PHGETPROCESSIMAGEFILENAME                               1542
#define EXPORT_PHGETPROCESSIMAGEFILENAMEBYPROCESSID                    1543
#define EXPORT_PHGETPROCESSIMAGEFILENAMEWIN32                          1544
#define EXPORT_PHGETPROCESSISDOTNET                                    1545
#define EXPORT_PHGETPROCESSISDOTNETEX                                  1546
#define EXPORT_PHGETPROCESSMAPPEDFILENAME                              1547
#define EXPORT_PHGETPROCESSPEBSTRING                                   1548
#define EXPORT_PHGETPROCESSPRIORITYCLASS                               1549
#define EXPORT_PHGETPROCESSUNLOADEDDLLS                                1550
#define EXPORT_PHGETPROCESSWINDOWTITLE                                 1551
#define EXPORT_PHGETPROCESSWORKINGSETINFORMATION                       1552
#define EXPORT_PHGETPROCESSWSCOUNTERS                                  1553
#define EXPORT_PHGETSECTIONFILENAME                                    1554
#define EXPORT_PHGETTOKENGROUPS                                        1555
#define EXPORT_PHGETTOKENINTEGRITYLEVEL                                1556
#define EXPORT_PHGETTOKENINTEGRITYLEVELRID                             1557
#define EXPORT_PHGETTOKENOWNER                                         1558
#define EXPORT_PHGETTOKENPRIMARYGROUP                                  1559
#define EXPORT_PHGETTOKENPRIVILEGES                                    1560
#define EXPORT_PHGETTOKENUSER                                          1561
#define EXPORT_PHIMPERSONATETOKEN                                      1562
#define EXPORT_PHISDEBUGGERPRESENT                                     1563
#define EXPORT_PHISFIRMWARESUPPORTED                                   1564
#define EXPORT_PHLISTENNAMEDPIPE                                       1565
#define EXPORT_PHLOADAPPKEY                                            1566
#define EXPORT_PHMOVEFILEWIN32                                         1567
#define EXPORT_PHOPENDIRECTORYOBJECT                                   1568
#define EXPORT_PHOPENDRIVER                                            1569
#define EXPORT_PHOPENFILE                                              1570
#define EXPORT_PHOPENFILEBYID                                          1571
#define EXPORT_PHOPENKEY                                               1572
#define EXPORT_PHOPENPROCESS                                           1573
#define EXPORT_PHOPENPROCESSCLIENTID                                   1574
#define EXPORT_PHOPENPROCESSTOKEN                                      1575
#define EXPORT_PHOPENTHREAD                                            1576
#define EXPORT_PHOPENTHREADPROCESS                                     1577
#define EXPORT_PHPEEKNAMEDPIPE                                         1578
#define EXPORT_PHQUERYENVIRONMENTVARIABLE                              1579
#define EXPORT_PHQUERYFULLATTRIBUTESFILEWIN32                          1580
#define EXPORT_PHQUERYKEY                                              1581
#define EXPORT_PHQUERYSYMBOLICLINKOBJECT                               1582
#define EXPORT_PHQUERYTOKENVARIABLESIZE                                1583
#define EXPORT_PHQUERYVALUEKEY                                         1584
#define EXPORT_PHQUEUEUSERWORKITEM                                     1585
#define EXPORT_PHREADFILE                                              1586
#define EXPORT_PHRESOLVEDEVICEPREFIX                                   1587
#define EXPORT_PHREVERTIMPERSONATIONTOKEN                              1588
#define EXPORT_PHSETFILEALLOCATIONSIZE                                 1589
#define EXPORT_PHSETFILEPOSITION                                       1590
#define EXPORT_PHSETFILESIZE                                           1591
#define EXPORT_PHSETFIRMWAREENVIRONMENTVARIABLE                        1592
#define EXPORT_PHSETOBJECTSECURITY                                     1593
#define EXPORT_PHSETPROCESSPOWERTHROTTLINGSTATE                        1594
#define EXPORT_PHSETPROCESSPRIORITYBOOST                               1595
#define EXPORT_PHSETPROCESSPRIORITYCLASS                               1596
#define EXPORT_PHSETTHREADBASEPRIORITY                                 1597
#define EXPORT_PHSETTHREADIOPRIORITY                                   1598
#define EXPORT_PHSETTHREADNAME                                         1599
#define EXPORT_PHSETTOKENISVIRTUALIZATIONENABLED                       1600
#define EXPORT_PHSETTOKENPRIVILEGE                                     1601
#define EXPORT_PHSETTOKENPRIVILEGE2                                    1602
#define EXPORT_PHSETTOKENSESSIONID                                     1603
#define EXPORT_PHSETVALUEKEY                                           1604
#define EXPORT_PHTERMINATEPROCESS                                      1605
#define EXPORT_PHTRACECONTROL                                          1606
#define EXPORT_PHTRANSCEIVENAMEDPIPE                                   1607
#define EXPORT_PHUNLOADDLLPROCESS                                      1608
#define EXPORT_PHUNLOADDRIVER                                          1609
#define EXPORT_PHUPDATEDOSDEVICEPREFIXES                               1610
#define EXPORT_PHUPDATEMUPDEVICEPREFIXES                               1611
#define EXPORT_PHWAITFORNAMEDPIPE                                      1612
#define EXPORT_PHWRITEFILE                                             1613
#define EXPORT_PHADJUSTRECTANGLETOBOUNDS                               1614
#define EXPORT_PHADJUSTRECTANGLETOWORKINGAREA                          1615
#define EXPORT_PHCENTERRECTANGLE                                       1616
#define EXPORT_PHCENTERWINDOW                                          1617
#define EXPORT_PHCOMPAREUNICODESTRINGZIGNOREMENUPREFIX                 1618
#define EXPORT_PHCONSOLESETFOREGROUND                                  1619
#define EXPORT_PHCONSOLESETWINDOW                                      1620
#define EXPORT_PHCREATEOPENFILEDIALOG                                  1621
#define EXPORT_PHCREATEPROCESS                                         1622
#define EXPORT_PHCREATEPROCESSASUSER                                   1623
#define EXPORT_PHCREATEPROCESSREDIRECTION                              1624
#define EXPORT_PHCREATEPROCESSWIN32                                    1625
#define EXPORT_PHCREATEPROCESSWIN32EX                                  1626
#define EXPORT_PHCREATESAVEFILEDIALOG                                  1627
#define EXPORT_PHDELETEIMAGEVERSIONINFO                                1628
#define EXPORT_PHDEVFREEOBJECTPROPERTIES                               1629
#define EXPORT_PHDEVFREEOBJECTS                                        1630
#define EXPORT_PHDEVGETOBJECTPROPERTIES                                1631
#define EXPORT_PHDEVGETOBJECTS                                         1632
#define EXPORT_PHELLIPSISSTRING                                        1633
#define EXPORT_PHELLIPSISSTRINGPATH                                    1634
#define EXPORT_PHESCAPECOMMANDLINEPART                                 1635
#define EXPORT_PHESCAPESTRINGFORMENUPREFIX                             1636
#define EXPORT_PHEXPANDENVIRONMENTSTRINGS                              1637
#define EXPORT_PHFILEREADALLTEXTWIN32                                  1638
#define EXPORT_PHFINALHASH                                             1639
#define EXPORT_PHFORMATDATE                                            1640
#define EXPORT_PHFORMATDATETIME                                        1641
#define EXPORT_PHFORMATDECIMAL                                         1642
#define EXPORT_PHFORMATGUID                                            1643
#define EXPORT_PHFORMATIMAGEVERSIONINFO                                1644
#define EXPORT_PHFORMATSIZE                                            1645
#define EXPORT_PHFORMATTIME                                            1646
#define EXPORT_PHFORMATTIMESPAN                                        1647
#define EXPORT_PHFORMATTIMESPANRELATIVE                                1648
#define EXPORT_PHFORMATUINT64                                          1649
#define EXPORT_PHFREEFILEDIALOG                                        1650
#define EXPORT_PHFREELIBRARY                                           1651
#define EXPORT_PHFREELIBRARYASIMAGERESOURCE                            1652
#define EXPORT_PHGENERATEGUID                                          1653
#define EXPORT_PHGENERATEGUIDFROMNAME                                  1654
#define EXPORT_PHGENERATERANDOMALPHASTRING                             1655
#define EXPORT_PHGENERATERANDOMNUMBER64                                1656
#define EXPORT_PHGETAPPLICATIONDATAFILENAME                            1657
#define EXPORT_PHGETAPPLICATIONDIRECTORY                               1658
#define EXPORT_PHGETAPPLICATIONDIRECTORYFILENAME                       1659
#define EXPORT_PHGETAPPLICATIONDIRECTORYWIN32                          1660
#define EXPORT_PHGETAPPLICATIONFILENAMEWIN32                           1661
#define EXPORT_PHGETBASEDIRECTORY                                      1662
#define EXPORT_PHGETBASENAME                                           1663
#define EXPORT_PHGETCLASSOBJECT                                        1664
#define EXPORT_PHGETDLLFILENAME                                        1665
#define EXPORT_PHGETCLIENTRECT                                         1666
#define EXPORT_PHGETDPI                                                1667
#define EXPORT_PHGETDPIVALUE                                           1668
#define EXPORT_PHGETFILEDIALOGFILENAME                                 1669
#define EXPORT_PHGETFILEDIALOGFILTERINDEX                              1670
#define EXPORT_PHGETFILEDIALOGOPTIONS                                  1671
#define EXPORT_PHGETFILEVERSIONFIXEDINFO                               1672
#define EXPORT_PHGETFILEVERSIONINFO                                    1673
#define EXPORT_PHGETFILEVERSIONINFOEX                                  1674
#define EXPORT_PHGETFILEVERSIONINFOLANGCODEPAGE                        1675
#define EXPORT_PHGETFILEVERSIONINFOSTRING                              1676
#define EXPORT_PHGETFILEVERSIONINFOSTRING2                             1677
#define EXPORT_PHGETFULLPATH                                           1678
#define EXPORT_PHGETKNOWNFOLDERPATH                                    1679
#define EXPORT_PHGETKNOWNLOCATION                                      1680
#define EXPORT_PHGETMESSAGE                                            1681
#define EXPORT_PHGETMONITORDPI                                         1682
#define EXPORT_PHGETNTMESSAGE                                          1683
#define EXPORT_PHGETNTSYSTEMROOT                                       1684
#define EXPORT_PHGETSIZEDPIVALUE                                       1685
#define EXPORT_PHGETSTATUSMESSAGE                                      1686
#define EXPORT_PHGETSYSTEMDIRECTORY                                    1687
#define EXPORT_PHGETSYSTEMDPI                                          1688
#define EXPORT_PHGETSYSTEMMETRICS                                      1689
#define EXPORT_PHGETSYSTEMPARAMETERSINFO                               1690
#define EXPORT_PHGETSYSTEMROOT                                         1691
#define EXPORT_PHGETTASKBARDPI                                         1692
#define EXPORT_PHGETTEMPORARYDIRECTORYRANDOMALPHAFILENAME              1693
#define EXPORT_PHGETWIN32MESSAGE                                       1694
#define EXPORT_PHGETWINDOWDPI                                          1695
#define EXPORT_PHINITIALIZEHASH                                        1696
#define EXPORT_PHINITIALIZEIMAGEVERSIONINFO                            1697
#define EXPORT_PHINITIALIZEIMAGEVERSIONINFOEX                          1698
#define EXPORT_PHINITIALIZEPROCTHREADATTRIBUTELIST                     1699
#define EXPORT_PHLARGEINTEGERTOLOCALSYSTEMTIME                         1700
#define EXPORT_PHLARGEINTEGERTOSYSTEMTIME                              1701
#define EXPORT_PHLOADLIBRARY                                           1702
#define EXPORT_PHLOADLIBRARYASIMAGERESOURCE                            1703
#define EXPORT_PHMAPFLAGS1                                             1704
#define EXPORT_PHMAPFLAGS2                                             1705
#define EXPORT_PHMATCHWILDCARDS                                        1706
#define EXPORT_PHPARSECOMMANDLINE                                      1707
#define EXPORT_PHPARSECOMMANDLINEFUZZY                                 1708
#define EXPORT_PHPARSECOMMANDLINEPART                                  1709
#define EXPORT_PHQUERYREGISTRYSTRING                                   1710
#define EXPORT_PHQUERYREGISTRYULONG                                    1711
#define EXPORT_PHQUERYREGISTRYULONG64                                  1712
#define EXPORT_PHSETFILEDIALOGFILENAME                                 1713
#define EXPORT_PHSETFILEDIALOGFILTER                                   1714
#define EXPORT_PHSETFILEDIALOGOPTIONS                                  1715
#define EXPORT_PHSHELLEXECUTE                                          1716
#define EXPORT_PHSHELLEXECUTEEX                                        1717
#define EXPORT_PHSHELLEXPLOREFILE                                      1718
#define EXPORT_PHSHELLPROPERTIES                                       1719
#define EXPORT_PHSHOWCONFIRMMESSAGE                                    1720
#define EXPORT_PHSHOWCONTINUESTATUS                                    1721
#define EXPORT_PHSHOWFILEDIALOG                                        1722
#define EXPORT_PHSHOWMESSAGE                                           1723
#define EXPORT_PHSHOWMESSAGE2                                          1724
#define EXPORT_PHSHOWMESSAGEONETIME                                    1725
#define EXPORT_PHSHOWSTATUS                                            1726
#define EXPORT_PHSHOWTASKDIALOG                                        1727
#define EXPORT_PHSTRINGTOGUID                                          1728
#define EXPORT_PHSYSTEMTIMETOLARGEINTEGER                              1729
#define EXPORT_PHSYSTEMTIMETOTZSPECIFICLOCALTIME                       1730
#define EXPORT_PHTASKBARLISTCREATE                                     1731
#define EXPORT_PHTASKBARLISTDESTROY                                    1732
#define EXPORT_PHTASKBARLISTSETOVERLAYICON                             1733
#define EXPORT_PHTASKBARLISTSETPROGRESSSTATE                           1734
#define EXPORT_PHTASKBARLISTSETPROGRESSVALUE                           1735
#define EXPORT_PHUPDATEHASH                                            1736
#define EXPORT_PHUPDATEPROCTHREADATTRIBUTE                             1737
#define EXPORT_PHWAITFORMULTIPLEOBJECTSANDPUMP                         1738
#define EXPORT_PHCLEARCIRCULARBUFFER_FLOAT                             1739
#define EXPORT_PHCLEARCIRCULARBUFFER_PVOID                             1740
#define EXPORT_PHCLEARCIRCULARBUFFER_ULONG                             1741
#define EXPORT_PHCLEARCIRCULARBUFFER_ULONG64                           1742
#define EXPORT_PHCOPYCIRCULARBUFFER_FLOAT                              1743
#define EXPORT_PHCOPYCIRCULARBUFFER_PVOID                              1744
#define EXPORT_PHCOPYCIRCULARBUFFER_ULONG                              1745
#define EXPORT_PHCOPYCIRCULARBUFFER_ULONG64                            1746
#define EXPORT_PHDELETECIRCULARBUFFER_FLOAT                            1747
#define EXPORT_PHDELETECIRCULARBUFFER_PVOID                            1748
#define EXPORT_PHDELETECIRCULARBUFFER_ULONG                            1749
#define EXPORT_PHDELETECIRCULARBUFFER_ULONG64                          1750
#define EXPORT_PHINITIALIZECIRCULARBUFFER_FLOAT                        1751
#define EXPORT_PHINITIALIZECIRCULARBUFFER_PVOID                        1752
#define EXPORT_PHINITIALIZECIRCULARBUFFER_ULONG                        1753
#define EXPORT_PHINITIALIZECIRCULARBUFFER_ULONG64                      1754
#define EXPORT_PHRESIZECIRCULARBUFFER_FLOAT                            1755
#define EXPORT_PHRESIZECIRCULARBUFFER_PVOID                            1756
#define EXPORT_PHRESIZECIRCULARBUFFER_ULONG                            1757
#define EXPORT_PHRESIZECIRCULARBUFFER_ULONG64                          1758
#define EXPORT_PHGETGENERICTREENEWLINES                                1759
#define EXPORT_PHGETLISTVIEWITEMTEXT                                   1760
#define EXPORT_PHGETLISTVIEWSELECTEDITEMTEXT                           1761
#define EXPORT_PHGETTREENEWTEXT                                        1762
#define EXPORT_PHCREATEEMENU                                           1763
#define EXPORT_PHCREATEEMENUITEM                                       1764
#define EXPORT_PHDESTROYEMENU                                          1765
#define EXPORT_PHDESTROYEMENUITEM                                      1766
#define EXPORT_PHFINDEMENUITEM                                         1767
#define EXPORT_PHINDEXOFEMENUITEM                                      1768
#define EXPORT_PHINSERTEMENUITEM                                       1769
#define EXPORT_PHLOADRESOURCEEMENUITEM                                 1770
#define EXPORT_PHMODIFYEMENUITEM                                       1771
#define EXPORT_PHREMOVEALLEMENUITEMS                                   1772
#define EXPORT_PHREMOVEEMENUITEM                                       1773
#define EXPORT_PHSETFLAGSALLEMENUITEMS                                 1774
#define EXPORT_PHSETFLAGSEMENUITEM                                     1775
#define EXPORT_PHSHOWEMENU                                             1776
#define EXPORT_PHDELETEFASTLOCK                                        1777
#define EXPORT_PHINITIALIZEFASTLOCK                                    1778
#define EXPORT_PHFACQUIREFASTLOCKEXCLUSIVE                             1779
#define EXPORT_PHFACQUIREFASTLOCKSHARED                                1780
#define EXPORT_PHFRELEASEFASTLOCKEXCLUSIVE                             1781
#define EXPORT_PHFRELEASEFASTLOCKSHARED                                1782
#define EXPORT_PHFTRYACQUIREFASTLOCKEXCLUSIVE                          1783
#define EXPORT_PHFTRYACQUIREFASTLOCKSHARED                             1784
#define EXPORT_PHCREATEFILESTREAM                                      1785
#define EXPORT_PHCREATEFILESTREAM2                                     1786
#define EXPORT_PHFLUSHFILESTREAM                                       1787
#define EXPORT_PHGETPOSITIONFILESTREAM                                 1788
#define EXPORT_PHLOCKFILESTREAM                                        1789
#define EXPORT_PHREADFILESTREAM                                        1790
#define EXPORT_PHSEEKFILESTREAM                                        1791
#define EXPORT_PHUNLOCKFILESTREAM                                      1792
#define EXPORT_PHVERIFYFILESTREAM                                      1793
#define EXPORT_PHWRITEFILESTREAM                                       1794
#define EXPORT_PHWRITESTRINGASUTF8FILESTREAM                           1795
#define EXPORT_PHWRITESTRINGASUTF8FILESTREAMEX                         1796
#define EXPORT_PHWRITESTRINGFORMATASUTF8FILESTREAM                     1797
#define EXPORT_PHWRITESTRINGFORMATASUTF8FILESTREAM_V                   1798
#define EXPORT_PHDELETEGRAPHSTATE                                      1799
#define EXPORT_PHDRAWGRAPHDIRECT                                       1800
#define EXPORT_PHDRAWTRAYICONTEXT                                      1801
#define EXPORT_PHGETDRAWINFOGRAPHBUFFERS                               1802
#define EXPORT_PHGRAPHSTATEGETDRAWINFO                                 1803
#define EXPORT_PHINITIALIZEGRAPHSTATE                                  1804
#define EXPORT_PHNFGETTRAYICONFONT                                     1805
#define EXPORT_PHSETGRAPHTEXT                                          1806
#define EXPORT_PHADDLAYOUTITEM                                         1807
#define EXPORT_PHADDLAYOUTITEMEX                                       1808
#define EXPORT_PHADDLISTVIEWCOLUMN                                     1809
#define EXPORT_PHADDILISTVIEWCOLUMN                                    1810
#define EXPORT_PHADDILISTVIEWGROUP                                     1811
#define EXPORT_PHADDILISTVIEWGROUPITEM                                 1812
#define EXPORT_PHADDLISTVIEWGROUP                                      1813
#define EXPORT_PHADDLISTVIEWGROUPITEM                                  1814
#define EXPORT_PHADDLISTVIEWITEM                                       1815
#define EXPORT_PHADDILISTVIEWITEM                                      1816
#define EXPORT_PHADDTABCONTROLTAB                                      1817
#define EXPORT_PHBITMAPSETALPHA                                        1818
#define EXPORT_PHCREATEDIALOG                                          1819
#define EXPORT_PHCREATEWINDOWEX                                        1820
#define EXPORT_PHDELETELAYOUTMANAGER                                   1821
#define EXPORT_PHDIALOGBOX                                             1822
#define EXPORT_PHENUMCHILDWINDOWS                                      1823
#define EXPORT_PHENUMWINDOWS                                           1824
#define EXPORT_PHFINDILISTVIEWITEMBYFLAGS                              1825
#define EXPORT_PHFINDLISTVIEWITEMBYFLAGS                               1826
#define EXPORT_PHFINDLISTVIEWITEMBYPARAM                               1827
#define EXPORT_PHGETCOMBOBOXSTRING                                     1828
#define EXPORT_PHGETDIALOGITEMVALUE                                    1829
#define EXPORT_PHGETILISTVIEWITEMPARAM                                 1830
#define EXPORT_PHGETLISTBOXSTRING                                      1831
#define EXPORT_PHGETLISTVIEWITEMIMAGEINDEX                             1832
#define EXPORT_PHGETLISTVIEWITEMPARAM                                  1833
#define EXPORT_PHGETSELECTEDLISTVIEWITEMPARAM                          1834
#define EXPORT_PHGETSELECTEDLISTVIEWITEMPARAMS                         1835
#define EXPORT_PHGETSELECTEDILISTVIEWITEMPARAMS                        1836
#define EXPORT_PHGETSTOCKAPPLICATIONICON                               1837
#define EXPORT_PHGETSTOCKOBJECT                                        1838
#define EXPORT_PHGETWINDOWCLIENTID                                     1839
#define EXPORT_PHGETWINDOWCONTEXT                                      1840
#define EXPORT_PHGETWINDOWTEXT                                         1841
#define EXPORT_PHGETWINDOWTEXTEX                                       1842
#define EXPORT_PHICONTOBITMAP                                          1843
#define EXPORT_PHIMAGELISTADDBITMAP                                    1844
#define EXPORT_PHIMAGELISTADDICON                                      1845
#define EXPORT_PHIMAGELISTCREATE                                       1846
#define EXPORT_PHIMAGELISTDESTROY                                      1847
#define EXPORT_PHIMAGELISTDRAWEX                                       1848
#define EXPORT_PHIMAGELISTDRAWICON                                     1849
#define EXPORT_PHIMAGELISTGETICON                                      1850
#define EXPORT_PHIMAGELISTREMOVEICON                                   1851
#define EXPORT_PHIMAGELISTREPLACE                                      1852
#define EXPORT_PHIMAGELISTSETBKCOLOR                                   1853
#define EXPORT_PHIMAGELISTSETICONSIZE                                  1854
#define EXPORT_PHIMAGELISTSETIMAGECOUNT                                1855
#define EXPORT_PHINITIALIZELAYOUTMANAGER                               1856
#define EXPORT_PHLAYOUTMANAGERLAYOUT                                   1857
#define EXPORT_PHLOADICON                                              1858
#define EXPORT_PHLOADIMAGEFORMATFROMRESOURCE                           1859
#define EXPORT_PHMODALPROPERTYSHEET                                    1860
#define EXPORT_PHQUERYDIRECTXEXCLUSIVEOWNERSHIP                        1861
#define EXPORT_PHINITIALIZEWINDOWTHEME                                 1862
#define EXPORT_PHREINITIALIZEWINDOWTHEME                               1863
#define EXPORT_PHREGISTERWINDOWCALLBACK                                1864
#define EXPORT_PHREMOVELISTVIEWITEM                                    1865
#define EXPORT_PHREMOVEWINDOWCONTEXT                                   1866
#define EXPORT_PHSELECTCOMBOBOXSTRING                                  1867
#define EXPORT_PHSETCLIPBOARDSTRING                                    1868
#define EXPORT_PHSETCONTROLTHEME                                       1869
#define EXPORT_PHSETDIALOGITEMTEXT                                     1870
#define EXPORT_PHSETDIALOGITEMVALUE                                    1871
#define EXPORT_PHSETEXTENDEDLISTVIEW                                   1872
#define EXPORT_PHSETGROUPBOXTEXT                                       1873
#define EXPORT_PHSETHEADERSORTICON                                     1874
#define EXPORT_PHSETIMAGELISTBITMAP                                    1875
#define EXPORT_PHSETLISTVIEWITEMIMAGEINDEX                             1876
#define EXPORT_PHSETLISTVIEWITEMPARAM                                  1877
#define EXPORT_PHSETLISTVIEWSUBITEM                                    1878
#define EXPORT_PHSETILISTVIEWSUBITEM                                   1879
#define EXPORT_PHSETSTATEALLLISTVIEWITEMS                              1880
#define EXPORT_PHSETWINDOWCONTEXT                                      1881
#define EXPORT_PHSETWINDOWTEXT                                         1882
#define EXPORT_PHTHEMEWINDOWDRAWREBAR                                  1883
#define EXPORT_PHTHEMEWINDOWDRAWTOOLBAR                                1884
#define EXPORT_PHUNREGISTERWINDOWCALLBACK                              1885
#define EXPORT_PHWINDOWTHEMECONTROLCOLOR                               1886
#define EXPORT_PHCALLKPHQUERYFILEINFORMATIONWITHTIMEOUT                1887
#define EXPORT_PHCOMPAREOBJECTS                                        1888
#define EXPORT_PHENUMOBJECTTYPES                                       1889
#define EXPORT_PHFORMATNATIVEKEYNAME                                   1890
#define EXPORT_PHGETETWPUBLISHERNAME                                   1891
#define EXPORT_PHGETHANDLEINFORMATION                                  1892
#define EXPORT_PHGETHANDLEINFORMATIONEX                                1893
#define EXPORT_PHGETOBJECTTYPENAME                                     1894
#define EXPORT_PHQUERYOBJECTNAME                                       1895
#define EXPORT_PHSTDGETCLIENTIDNAME                                    1896
#define EXPORT_PHENUMERATEPRIVILEGES                                   1897
#define EXPORT_PHGETSIDFULLNAME                                        1898
#define EXPORT_PHLOOKUPNAME                                            1899
#define EXPORT_PHLOOKUPPRIVILEGEDISPLAYNAME                            1900
#define EXPORT_PHLOOKUPPRIVILEGENAME                                   1901
#define EXPORT_PHLOOKUPPRIVILEGEVALUE                                  1902
#define EXPORT_PHLOOKUPSID                                             1903
#define EXPORT_PHOPENLSAPOLICY                                         1904
#define EXPORT_PHSIDTOSTRINGSID                                        1905
#define EXPORT_PHLOADMAPPEDIMAGE                                       1906
#define EXPORT_PHLOADMAPPEDIMAGEEX                                     1907
#define EXPORT_PHLOADMAPPEDIMAGEHEADERPAGESIZE                         1908
#define EXPORT_PHUNLOADMAPPEDIMAGE                                     1909
#define EXPORT_PHBOOSTPROVIDER                                         1910
#define EXPORT_PHDELETEPROVIDERTHREAD                                  1911
#define EXPORT_PHGETENABLEDPROVIDER                                    1912
#define EXPORT_PHINITIALIZEPROVIDERTHREAD                              1913
#define EXPORT_PHREGISTERPROVIDER                                      1914
#define EXPORT_PHSETENABLEDPROVIDER                                    1915
#define EXPORT_PHSETINTERVALPROVIDERTHREAD                             1916
#define EXPORT_PHSTARTPROVIDERTHREAD                                   1917
#define EXPORT_PHSTOPPROVIDERTHREAD                                    1918
#define EXPORT_PHUNREGISTERPROVIDER                                    1919
#define EXPORT_PHADDSETTING                                            1920
#define EXPORT_PHADDSETTINGS                                           1921
#define EXPORT_PHCLEARIGNOREDSETTINGS                                  1922
#define EXPORT_PHCONVERTIGNOREDSETTINGS                                1923
#define EXPORT_PHGETINTEGERPAIRSTRINGREFSETTING                        1924
#define EXPORT_PHGETINTEGERSTRINGREFSETTING                            1925
#define EXPORT_PHGETSCALABLEINTEGERPAIRSTRINGREFSETTING                1926
#define EXPORT_PHGETSTRINGREFSETTING                                   1927
#define EXPORT_PHLOADCUSTOMCOLORLIST                                   1928
#define EXPORT_PHLOADLISTVIEWCOLUMNSETTINGS                            1929
#define EXPORT_PHLOADLISTVIEWCOLUMNSFROMSETTING                        1930
#define EXPORT_PHLOADLISTVIEWGROUPSTATESFROMSETTING                    1931
#define EXPORT_PHLOADLISTVIEWSORTCOLUMNSFROMSETTING                    1932
#define EXPORT_PHLOADSETTINGS                                          1933
#define EXPORT_PHLOADWINDOWPLACEMENTFROMSETTING                        1934
#define EXPORT_PHRESETSETTINGS                                         1935
#define EXPORT_PHSAVECUSTOMCOLORLIST                                   1936
#define EXPORT_PHSAVELISTVIEWCOLUMNSETTINGS                            1937
#define EXPORT_PHSAVELISTVIEWCOLUMNSTOSETTING                          1938
#define EXPORT_PHSAVELISTVIEWGROUPSTATESTOSETTING                      1939
#define EXPORT_PHSAVELISTVIEWSORTCOLUMNSTOSETTING                      1940
#define EXPORT_PHSAVESETTINGS                                          1941
#define EXPORT_PHSAVEWINDOWPLACEMENTTOSETTING                          1942
#define EXPORT_PHSETINTEGERPAIRSTRINGREFSETTING                        1943
#define EXPORT_PHSETINTEGERSTRINGREFSETTING                            1944
#define EXPORT_PHSETSCALABLEINTEGERPAIRSTRINGREFSETTING                1945
#define EXPORT_PHSETSCALABLEINTEGERPAIRSTRINGREFSETTING2               1946
#define EXPORT_PHSETSTRINGREFSETTING                                   1947
#define EXPORT_PHUPDATECACHEDSETTINGS                                  1948
#define EXPORT_PHCREATESECURITYPAGE                                    1949
#define EXPORT_PHEDITSECURITY                                          1950
#define EXPORT_PHGETACCESSENTRIES                                      1951
#define EXPORT_PHGETACCESSSTRING                                       1952
#define EXPORT_PHGETSEOBJECTSECURITY                                   1953
#define EXPORT_PHSETSEOBJECTSECURITY                                   1954
#define EXPORT_PHSTDGETOBJECTSECURITY                                  1955
#define EXPORT_PHSTDSETOBJECTSECURITY                                  1956
#define EXPORT_PHCHANGESERVICECONFIG2                                  1957
#define EXPORT_PHCLOSESERVICEHANDLE                                    1958
#define EXPORT_PHENUMDEPENDENTSERVICES                                 1959
#define EXPORT_PHGETSERVICECONFIG                                      1960
#define EXPORT_PHGETSERVICECONFIGFILENAME                              1961
#define EXPORT_PHGETSERVICEDESCRIPTION                                 1962
#define EXPORT_PHGETSERVICEDLLPARAMETER                                1963
#define EXPORT_PHGETSERVICEERRORCONTROLINTEGER                         1964
#define EXPORT_PHGETSERVICEERRORCONTROLSTRING                          1965
#define EXPORT_PHGETSERVICEFILENAME                                    1966
#define EXPORT_PHGETSERVICENAMEFROMTAG                                 1967
#define EXPORT_PHGETSERVICESTARTTYPEINTEGER                            1968
#define EXPORT_PHGETSERVICESTARTTYPESTRING                             1969
#define EXPORT_PHGETSERVICESTATESTRING                                 1970
#define EXPORT_PHGETSERVICETYPEINTEGER                                 1971
#define EXPORT_PHGETSERVICETYPESTRING                                  1972
#define EXPORT_PHGETTHREADSERVICETAG                                   1973
#define EXPORT_PHOPENSERVICE                                           1974
#define EXPORT_PHOPENSERVICEKEY                                        1975
#define EXPORT_PHQUERYSERVICECONFIG                                    1976
#define EXPORT_PHQUERYSERVICECONFIG2                                   1977
#define EXPORT_PHQUERYSERVICESTATUS                                    1978
#define EXPORT_PHQUERYSERVICEVARIABLESIZE                              1979
#define EXPORT_PHSTARTSERVICE                                          1980
#define EXPORT_PHSTOPSERVICE                                           1981
#define EXPORT_PHCREATESYMBOLPROVIDER                                  1982
#define EXPORT_PHGETLINEFROMADDRESS                                    1983
#define EXPORT_PHGETMODULEFROMADDRESS                                  1984
#define EXPORT_PHGETSYMBOLFROMADDRESS                                  1985
#define EXPORT_PHGETSYMBOLFROMNAME                                     1986
#define EXPORT_PHLOADSYMBOLPROVIDERMODULES                             1987
#define EXPORT_PHLOADMODULESYMBOLPROVIDER                              1988
#define EXPORT_PHLOADMODULESFORVIRTUALSYMBOLPROVIDER                   1989
#define EXPORT_PHSETOPTIONSSYMBOLPROVIDER                              1990
#define EXPORT_PHSETSEARCHPATHSYMBOLPROVIDER                           1991
#define EXPORT_PHSTACKWALK                                             1992
#define EXPORT_PHWALKTHREADSTACK                                       1993
#define EXPORT_PHWRITEMINIDUMPPROCESS                                  1994
#define EXPORT_PHVERIFYFILE                                            1995
#define EXPORT_PHVERIFYFILEISCHAINEDTOMICROSOFT                        1996
#define EXPORT_PHDELETEWORKQUEUE                                       1997
#define EXPORT_PHGETGLOBALWORKQUEUE                                    1998
#define EXPORT_PHINITIALIZEWORKQUEUE                                   1999
#define EXPORT_PHINITIALIZEWORKQUEUEENVIRONMENT                        2000
#define EXPORT_PHQUEUEITEMWORKQUEUE                                    2001
#define EXPORT_PHQUEUEITEMWORKQUEUEEX                                  2002
#define EXPORT_PHWAITFORWORKQUEUE                                      2003
#define EXPORT_PHADDJSONARRAYOBJECT                                    2004
#define EXPORT_PHADDJSONOBJECT                                         2005
#define EXPORT_PHADDJSONOBJECT2                                        2006
#define EXPORT_PHADDJSONOBJECTINT64                                    2007
#define EXPORT_PHADDJSONOBJECTUINT64                                   2008
#define EXPORT_PHADDJSONOBJECTVALUE                                    2009
#define EXPORT_PHCREATEJSONARRAY                                       2010
#define EXPORT_PHCREATEJSONOBJECT                                      2011
#define EXPORT_PHCREATEJSONPARSER                                      2012
#define EXPORT_PHCREATEJSONPARSEREX                                    2013
#define EXPORT_PHFREEJSONOBJECT                                        2014
#define EXPORT_PHGETJSONARRAYINDEXOBJECT                               2015
#define EXPORT_PHGETJSONARRAYLENGTH                                    2016
#define EXPORT_PHGETJSONARRAYLONG64                                    2017
#define EXPORT_PHGETJSONARRAYSTRING                                    2018
#define EXPORT_PHGETJSONOBJECT                                         2019
#define EXPORT_PHGETJSONOBJECTASARRAYLIST                              2020
#define EXPORT_PHGETJSONOBJECTBOOL                                     2021
#define EXPORT_PHGETJSONOBJECTLENGTH                                   2022
#define EXPORT_PHGETJSONOBJECTTYPE                                     2023
#define EXPORT_PHGETJSONVALUEASINT64                                   2024
#define EXPORT_PHGETJSONVALUEASSTRING                                  2025
#define EXPORT_PHGETJSONVALUEASUINT64                                  2026
#define EXPORT_PHCREATEXMLNODE                                         2027
#define EXPORT_PHCREATEXMLOPAQUENODE                                   2028
#define EXPORT_PHFINDXMLOBJECT                                         2029
#define EXPORT_PHFREEXMLOBJECT                                         2030
#define EXPORT_PHGETXMLINTERFACE                                       2031
#define EXPORT_PHGETXMLNODEATTRIBUTEBYINDEX                            2032
#define EXPORT_PHGETXMLNODEATTRIBUTECOUNT                              2033
#define EXPORT_PHGETXMLNODEATTRIBUTETEXT                               2034
#define EXPORT_PHGETXMLNODEELEMENTTEXT                                 2035
#define EXPORT_PHGETXMLNODEFIRSTCHILD                                  2036
#define EXPORT_PHGETXMLNODENEXTCHILD                                   2037
#define EXPORT_PHGETXMLNODEOPAQUETEXT                                  2038
#define EXPORT_PHGETXMLOBJECT                                          2039
#define EXPORT_PHLOADXMLOBJECTFROMFILE                                 2040
#define EXPORT_PHLOADXMLOBJECTFROMSTRING                               2041
#define EXPORT_PHSAVEXMLOBJECTTOFILE                                   2042
#define EXPORT_PHSETXMLNODEATTRIBUTETEXT                               2043
#define EXPORT_PHCLEARCACHEDIRECTORY                                   2044
#define EXPORT_PHCREATECACHEFILE                                       2045
#define EXPORT_PHDELETECACHEFILE                                       2046
#define EXPORT_PHAPPRESOLVERGETAPPIDFORWINDOW                          2047
#define EXPORT_PHGETPROCESSPACKAGEFULLNAME                             2048
#define EXPORT_PHDNSFREE                                               2049
#define EXPORT_PHDNSQUERY                                              2050
#define EXPORT_PHDNSQUERY2                                             2051
#define EXPORT_PHHTTPDNSQUERY                                          2052
#define EXPORT_PHHTTPSOCKETADDREQUESTHEADERS                           2053
#define EXPORT_PHHTTPSOCKETBEGINREQUEST                                2054
#define EXPORT_PHHTTPSOCKETCLOSE                                       2055
#define EXPORT_PHHTTPSOCKETCONNECT                                     2056
#define EXPORT_PHHTTPSOCKETCREATE                                      2057
#define EXPORT_PHHTTPSOCKETDESTROY                                     2058
#define EXPORT_PHHTTPSOCKETDOWNLOADSTRING                              2059
#define EXPORT_PHHTTPSOCKETENDREQUEST                                  2060
#define EXPORT_PHHTTPSOCKETGETERRORMESSAGE                             2061
#define EXPORT_PHHTTPSOCKETPARSEURL                                    2062
#define EXPORT_PHHTTPSOCKETQUERYHEADERSTRING                           2063
#define EXPORT_PHHTTPSOCKETQUERYHEADERULONG                            2064
#define EXPORT_PHHTTPSOCKETQUERYHEADERULONG64                          2065
#define EXPORT_PHHTTPSOCKETQUERYHEADERS                                2066
#define EXPORT_PHHTTPSOCKETQUERYOPTIONSTRING                           2067
#define EXPORT_PHHTTPSOCKETREADDATA                                    2068
#define EXPORT_PHHTTPSOCKETREADDATATOBUFFER                            2069
#define EXPORT_PHHTTPSOCKETSENDREQUEST                                 2070
#define EXPORT_PHHTTPSOCKETSETCREDENTIALS                              2071
#define EXPORT_PHHTTPSOCKETSETFEATURE                                  2072
#define EXPORT_PHHTTPSOCKETSETSECURITY                                 2073
#define EXPORT_PHHTTPSOCKETWRITEDATA                                   2074
#define EXPORT_KSILEVEL                                                2075
#define EXPORT_KPHALPCQUERYINFORMATION                                 2076
#define EXPORT_KPHDUPLICATEOBJECT                                      2077
#define EXPORT_KPHOPENDEVICE                                           2078
#define EXPORT_KPHOPENDEVICEBASEDEVICE                                 2079
#define EXPORT_KPHOPENDEVICEDRIVER                                     2080
#define EXPORT_KPHQUERYINFORMATIONDRIVER                               2081
#define EXPORT_KPHQUERYINFORMATIONOBJECT                               2082
#define EXPORT_KSIENUMERATEPROCESSHANDLES                              2083
#define EXPORT_KSIQUERYHASHINFORMATIONFILE                             2084

#endif _PH_EXPORT_DEF_H