name: 'Bug report'
description: Report bugs or other issues
type: "Bug"
labels: ["needs-triage"]
body:
  - type: textarea
    attributes:
      label: Brief description of your issue
      placeholder: Briefly describe your issue here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce (optional)
      placeholder: How to reproduce the issue?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior (optional)
      placeholder: What did you expect to happen?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Actual behavior (optional)
      placeholder: What is currently happening?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment (optional)
      placeholder: |
        System Informer version
        Windows version
        Any other information?
      render: shell
    validations:
      required: false
