//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ExtendedTools.rc
//
#define ID_PROCESS_UNLOADEDMODULES      101
#define IDD_UNLOADEDDLLS                102
#define ID_THREAD_CANCELIO              104
#define IDD_OBJTPWORKERFACTORY          105
#define ID_MODULE_SERVICES              106
#define IDD_MODSERVICES                 107
#define ID_VIEW_MEMORYLISTS             108
#define IDD_PROCDISKNET                 110
#define ID_VIEW_DISKANDNETWORK          111
#define ID_PROCESS_WSWATCH              112
#define IDD_SYSINFO_DISKPANEL           113
#define IDD_OPTIONS                     114
#define IDD_WSWATCH                     115
#define IDD_SYSINFO_GPU                 117
#define IDR_DISK                        118
#define ID_VIEW_GPUINFORMATION          119
#define IDD_SYSINFO_GPUPANEL            120
#define IDD_PROCGPU                     121
#define IDD_SYSINFO_DISK                122
#define IDD_GPUNODES                    123
#define IDD_SYSINFO_NETPANEL            124
#define IDD_SYSINFO_NET                 125
#define IDD_PROCDISKNET_PANEL           129
#define IDC_UTILIZATION                 132
#define IDC_SPEED                       133
#define IDD_SYSINFO_GPUDETAILS          141
#define IDD_PROCFRAMES                  142
#define IDC_LIST                        1001
#define IDC_REFRESH                     1002
#define IDC_WORKERTHREADSTART           1005
#define IDC_WORKERTHREADCONTEXT         1006
#define IDC_SERVICES_LAYOUT             1007
#define IDC_MESSAGE                     1008
#define IDC_ZREADS_V                    1023
#define IDC_ZREADBYTES_V                1024
#define IDC_ZREADBYTESDELTA_V           1025
#define IDC_ZWRITES_V                   1026
#define IDC_ZWRITEBYTES_V               1027
#define IDC_ZWRITEBYTESDELTA_V          1028
#define IDC_ZRECEIVES_V                 1029
#define IDC_ZRECEIVEBYTES_V             1030
#define IDC_ZRECEIVEBYTESDELTA_V        1031
#define IDC_ZSENDS_V                    1032
#define IDC_ZSENDBYTES_V                1033
#define IDC_ZSENDBYTESDELTA_V           1034
#define IDC_ENABLEETWMONITOR            1035
#define IDC_ENABLE                      1036
#define IDC_WSWATCHENABLED              1037
#define IDC_ENABLEFAHRENHEITTEMP        1038
#define IDC_NODES                       1048
#define IDC_ENABLEGPUMONITOR            1049
#define IDC_ENABLESYSINFOGRAPHS         1050
#define IDC_GROUPGPU                    1051
#define IDC_ENABLEFWMONITOR             1051
#define IDC_ENABLEFPSMONITOR            1051
#define IDC_GROUPMEM                    1052
#define IDC_GROUPSHARED                 1053
#define IDC_GROUPCOMMIT                 1054
#define IDC_ZDEDICATEDCURRENT_V         1055
#define IDC_GROUPFPSFRAMERENDER         1055
#define IDC_ZDEDICATEDLIMIT_V           1056
#define IDC_GROUPFPSFRAMEDISPLAY        1056
#define IDC_ZSHAREDCURRENT_V            1057
#define IDC_GROUPFPSDISPLAYLATENCY      1057
#define IDC_ZSHAREDLIMIT_V              1058
#define IDC_TITLE                       1073
#define IDC_GRAPH_LAYOUT                1074
#define IDC_LAYOUT                      1075
#define IDC_GPUNAME                     1076
#define IDC_GPU_L                       1077
#define IDC_DEDICATED_L                 1078
#define IDC_SHARED_L                    1079
#define IDC_ZRECEIVESDELTA_V            1080
#define IDC_ZSENDSDELTA_V               1081
#define IDC_ZWRITESDELTA_V              1082
#define IDC_ZREADSDELTA_V               1083
#define IDC_PANEL_LAYOUT                1085
#define IDC_GROUPDISK                   1088
#define IDC_GROUPNETWORK                1089
#define IDC_DETAILS                     1092
#define IDC_GPULIST                     1093
#define IDC_POWER_USAGE_L               1094
#define IDC_TEMPERATURE_L               1095
#define IDC_FAN_RPM_L                   1096
#define IDC_GROUPFPS                    1098
#define IDC_GROUPFPSLATENCY             1099
#define IDC_GROUPFPSPRESENT             1100
#define IDC_GROUPFPSPRESENTINTERVAL     1101
#define IDC_BUTTON1                     1103
#define IDC_POOL_AUTOSIZE_COLUMNS       1104
#define ID_POOL_TABLE                   3000
#define IDD_POOL                        3001
#define IDR_TXT_POOLTAGS                3002
#define IDD_BIGPOOL                     3003
#define IDC_POOLTREE                    3004
#define IDC_POOLSEARCH                  3005
#define IDC_POOLCLEAR                   3006
#define IDC_BIGPOOLLIST                 3007
#define ID_OBJMGR                       4000
#define IDD_OBJMGR                      4001
#define IDI_FOLDER                      4002
#define IDI_MUTANT                      4003
#define IDI_DRIVER                      4004
#define IDI_SECTION                     4005
#define IDI_LINK                        4006
#define IDI_KEY                         4007
#define IDI_PORT                        4008
#define IDI_SESSION                     4009
#define IDI_EVENT                       4010
#define IDI_DEVICE                      4011
#define IDI_UNKNOWN                     4012
#define IDC_OBJMGR_LIST                 4013
#define IDC_OBJMGR_TREE                 4014
#define ID_FIRMWARE                     5001
#define IDD_FIRMWARE                    5002
#define IDD_FIRMWARE_EDITVAR            5003
#define IDC_FIRMWARE_HEXEDITVAR         5004
#define IDC_FIRMWARE_REREAD             5005
#define IDC_FIRMWARE_WRITE              5006
#define IDC_FIRMWARE_SAVE               5007
#define IDC_FIRMWARE_BYTESPERROW        5008
#define IDC_FIRMWARE_BOOT_LIST          5009
#define IDC_FIRMWARE_BOOT_REFRESH       5010
#define ID_PIPE_ENUM                    6000
#define IDD_PIPEDIALOG                  6001
#define IDC_ATOMLIST                    6002
#define IDC_PIPELIST                    6002
#define ID_REPARSE_POINTS               7000
#define ID_REPARSE_OBJID                7001
#define ID_REPARSE_SDDL                 7002
#define IDD_REPARSEDIALOG               7003
#define IDC_REPARSE_LIST                7004
#define ID_PROCESS_WAITCHAIN            8000
#define ID_THREAD_WAITCHAIN             8001
#define ID_WCT_SHOWCONTEXTMENU          8001
#define IDD_WCT_DIALOG                  8002
#define IDC_WCT_TREE                    8004
#define ID_WCT_MENU_PROPERTIES          8007
#define ID_WCT_MENU_COPY                8008
#define ID_DISK_GOTOPROCESS             40005
#define ID_DISK_COPY                    40006
#define ID_DISK_PROPERTIES              40007
#define ID_DISK_OPENFILELOCATION        40008
#define ID_DISK_INSPECT                 40009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         40009
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           135
#endif
#endif
