// This file originally generated by etw_list
//     version:    development branch 1f6ac03eede3e9ab6a6bae5c6de68ad6dd75312d
//     parameters: --show=all --output=c++ --event=Present::Start --event=Present::Stop --event=PresentMultiplaneOverlay::Start --event=PresentMultiplaneOverlay::Stop --provider=Microsoft-Windows-DXGI
// Copyright (C) 2020-2021 Intel Corporation
// SPDX-License-Identifier: MIT
#pragma once

namespace Microsoft_Windows_DXGI {

struct __declspec(uuid("{CA11C036-0102-4A2D-A6AD-F03CFED5D3C9}")) GUID_STRUCT;
static const auto GUID = __uuidof(GUID_STRUCT);

enum class Keyword : uint64_t {
    Objects                         = 0x1,
    Events                          = 0x2,
    JournalEntries                  = 0x4,
    Microsoft_Windows_DXGI_Analytic = 0x8000000000000000,
    Microsoft_Windows_DXGI_Logging  = 0x4000000000000000,
};

enum class Level : uint8_t {
    win_LogAlways = 0x0,
};

enum class Channel : uint8_t {
    Microsoft_Windows_DXGI_Analytic = 0x10,
    Microsoft_Windows_DXGI_Logging  = 0x11,
};

// Event descriptors:
#define EVENT_DESCRIPTOR_DECL(name_, id_, version_, channel_, level_, opcode_, task_, keyword_) struct name_ { \
    static uint16_t const Id      = id_; \
    static uint8_t  const Version = version_; \
    static uint8_t  const Channel = channel_; \
    static uint8_t  const Level   = level_; \
    static uint8_t  const Opcode  = opcode_; \
    static uint16_t const Task    = task_; \
    static Keyword  const Keyword = (Keyword) keyword_; \
};

EVENT_DESCRIPTOR_DECL(Present_Start                 , 0x002a, 0x00, 0x10, 0x00, 0x01, 0x0009, 0x8000000000000002)
EVENT_DESCRIPTOR_DECL(Present_Stop                  , 0x002b, 0x00, 0x10, 0x00, 0x02, 0x0009, 0x8000000000000002)
EVENT_DESCRIPTOR_DECL(PresentMultiplaneOverlay_Start, 0x0037, 0x00, 0x10, 0x00, 0x01, 0x000e, 0x8000000000000002)
EVENT_DESCRIPTOR_DECL(PresentMultiplaneOverlay_Stop , 0x0038, 0x00, 0x10, 0x00, 0x02, 0x000e, 0x8000000000000002)

#undef EVENT_DESCRIPTOR_DECL

#pragma warning(push)
#pragma warning(disable: 4200) // nonstandard extension used: zero-sized array in struct

#pragma pack(push)
#pragma pack(1)

template<typename PointerT>
struct Present_Start_Struct {
    PointerT    pIDXGISwapChain;
    uint32_t    Flags;
    uint32_t    SyncInterval;
    uint32_t    DirtyRects;
    uint32_t    ScrollRects;
};

struct Present_Stop_Struct {
    uint32_t    Result;
};

template<typename PointerT>
struct PresentMultiplaneOverlay_Start_Struct {
    PointerT    pIDXGISwapChain;
    uint32_t    Flags;
    uint32_t    SyncInterval;
    uint32_t    NumPlanes;
    uint32_t    LayerMask;
};

struct PresentMultiplaneOverlay_Stop_Struct {
    uint32_t    Result;
};

#pragma pack(pop)
#pragma warning(pop)

}
