// This file originally generated by etw_list
//     version:    development branch 1f6ac03eede3e9ab6a6bae5c6de68ad6dd75312d
//     parameters: --show=all --output=c++ --event=MILEVENT_MEDIA_UCE_PROCESSPRESENTHISTORY_GetPresentHistory::Info --event=SCHEDULE_PRESENT::Start --event=SCHEDULE_SURFACEUPDATE::Info --provider=Microsoft-Windows-Dwm-Core
// Copyright (C) 2020-2021 Intel Corporation
// SPDX-License-Identifier: MIT
#pragma once

namespace Microsoft_Windows_Dwm_Core {

struct __declspec(uuid("{9E9BBA3C-2E38-40CB-99F4-9E8281425164}")) GUID_STRUCT;
static const auto GUID = __uuidof(GUID_STRUCT);

// Win7 GUID added manually:
namespace Win7 {
struct __declspec(uuid("{8c9dd1ad-e6e5-4b07-b455-684a9d879900}")) GUID_STRUCT;
static const auto GUID = __uuidof(GUID_STRUCT);
}

enum class Keyword : uint64_t {
    DwmCore                               = 0x1,
    DetailedFrameInformation              = 0x2,
    FrameDrawInconsistencyInformation     = 0x4,
    DwmFrameRate                          = 0x8,
    AnimationScreenOff                    = 0x10,
    ProcessAttribution                    = 0x20,
    ComputeScribble                       = 0x40,
    FrameVisualization                    = 0x10000,
    LowOverheadSmoothnessTracking         = 0x20000,
    FrameVisualizationExtra               = 0x40000,
    DwmHolographic                        = 0x80000,
    WorkPerFrame                          = 0x100000,
    DwmInput                              = 0x200000,
    DwmDiagTrack                          = 0x400000,
    WorkPerFrameVerbose                   = 0x800000,
    win_ResponseTime                      = 0x1000000000000,
    Microsoft_Windows_Dwm_Core_Diagnostic = 0x8000000000000000,
};

enum class Level : uint8_t {
    win_Error         = 0x2,
    win_Informational = 0x4,
    win_Verbose       = 0x5,
};

enum class Channel : uint8_t {
    Microsoft_Windows_Dwm_Core_Diagnostic = 0x10,
};

// Event descriptors:
#define EVENT_DESCRIPTOR_DECL(name_, id_, version_, channel_, level_, opcode_, task_, keyword_) struct name_ { \
    static uint16_t const Id      = id_; \
    static uint8_t  const Version = version_; \
    static uint8_t  const Channel = channel_; \
    static uint8_t  const Level   = level_; \
    static uint8_t  const Opcode  = opcode_; \
    static uint16_t const Task    = task_; \
    static Keyword  const Keyword = (Keyword) keyword_; \
};

EVENT_DESCRIPTOR_DECL(MILEVENT_MEDIA_UCE_PROCESSPRESENTHISTORY_GetPresentHistory_Info, 0x0040, 0x00, 0x10, 0x05, 0x00, 0x003f, 0x8000000000000001)
EVENT_DESCRIPTOR_DECL(SCHEDULE_PRESENT_Start                                         , 0x000f, 0x00, 0x10, 0x04, 0x01, 0x000d, 0x8000000000000001)
EVENT_DESCRIPTOR_DECL(SCHEDULE_SURFACEUPDATE_Info                                    , 0x00c4, 0x00, 0x10, 0x04, 0x00, 0x007f, 0x8000000000000001)

// These events added manually:
struct FlipChain_Pending  { static uint16_t const Id = 0x0045; };
struct FlipChain_Complete { static uint16_t const Id = 0x0046; };
struct FlipChain_Dirty    { static uint16_t const Id = 0x0065; };

#undef EVENT_DESCRIPTOR_DECL

#pragma warning(push)
#pragma warning(disable: 4200) // nonstandard extension used: zero-sized array in struct

#pragma pack(push)
#pragma pack(1)

struct MILEVENT_MEDIA_UCE_PROCESSPRESENTHISTORY_GetPresentHistory_Info_Struct {
    uint32_t    hr;
    uint32_t    cTokenCount;
};

struct SCHEDULE_PRESENT_Start_Struct {
    uint64_t    tCurrent;
    uint64_t    tPresent;
    uint64_t    cRefreshCurrent;
    uint64_t    cRefreshPresent;
    uint32_t    fForce;
};

struct SCHEDULE_SURFACEUPDATE_Info_MemberStruct_1_Struct {
    uint32_t    lowpart;
    uint32_t    highpart;
};

struct SCHEDULE_SURFACEUPDATE_Info_Struct {
    struct SCHEDULE_SURFACEUPDATE_Info_MemberStruct_1_Struct luidSurface[1];
    uint64_t    bindId;
    uint64_t    PresentCount;
    uint64_t    fenceValue;
    uint32_t    bDirectFlip;
    uint32_t    DXGI_ALPHA_MODE;
    uint64_t    hmonAssociation;
    uint32_t    bStereoPreferRight;
    uint32_t    bTemporaryMono;
    uint32_t    bSwapPool;
    uint32_t    BufferContentType;
    uint32_t    bIndependentFlip;
    uint32_t    uPesentDuration;
    uint32_t    BufferRealizationType;
    uint32_t    uRealizationIndex;
    uint64_t    hDxSurface;
};

#pragma pack(pop)
#pragma warning(pop)

}
