#ifndef ETPLUGINEXT_H
#define ETPLUGINEXT_H

#define EXTENDEDTOOLS_PLUGIN_NAME L"ProcessHacker.ExtendedTools"
#define EXTENDEDTOOLS_INTERFACE_VERSION 1

typedef FLOAT (NTAPI* PEXTENDEDTOOLS_GET_GPUENGINEUTILIZATION)(
    _In_ LUID EngineLuid
    );
typedef ULONG64 (NTAPI* PEXTENDEDTOOLS_GET_GPUENGINEDEDICATED)(
    _In_ LUID EngineLuid
    );
typedef ULONG64 (NTAPI* PEXTENDEDTOOLS_GET_GPUENGINESHARED)(
    _In_ LUID EngineLuid
    );

typedef struct _EXTENDEDTOOLS_INTERFACE
{
    ULONG Version;
    PEXTENDEDTOOLS_GET_GPUENGINEUTILIZATION GetGpuEngineUtilization;
    PEXTENDEDTOOLS_GET_GPUENGINEDEDICATED GetGpuEngineDedicated;
    PEXTENDEDTOOLS_GET_GPUENGINESHARED GetGpuEngineShared;
} EXTENDEDTOOLS_INTERFACE, *PEXTENDEDTOOLS_INTERFACE;

extern EXTENDEDTOOLS_INTERFACE PluginInterface;

#endif
