#
# Copyright (c) 2022 Winsider Seminars & Solutions, Inc.  All rights reserved.
#
# This file is part of System Informer.
#

set(CMAKE_MSVC_RUNTIME_CHECKS "")
set(CMAKE_MSVC_RUNTIME_LIBRARY "")
set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "")
set(CMAKE_C_FLAGS_INIT "")
set(CMAKE_C_FLAGS_DEBUG_INI "")
set(CMAKE_C_FLAGS_RELEASE_INIT "")
set(CMAKE_C_STANDARD_LIBRARIES_INIT "")
set(CMAKE_CXX_FLAGS_INIT "")
set(CMAKE_CXX_FLAGS_DEBUG_INIT "")
set(CMAKE_CXX_FLAGS_RELEASE_INIT "")
set(CMAKE_CXX_STANDARD_LIBRARIES_INIT "")
set(CMAKE_EXE_LINKER_FLAGS_INIT "")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT "")
set(CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT "")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "")
set(CMAKE_SHARED_LINKER_FLAGS_DEBUG_INIT "")
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE_INIT "")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "")
set(CMAKE_MODULE_LINKER_FLAGS_DEBUG_INIT "")
set(CMAKE_MODULE_LINKER_FLAGS_RELEASE_INIT "")
set(CMAKE_STATIC_LINKER_FLAGS_INIT "")
set(CMAKE_STATIC_LINKER_FLAGS_DEBUG_INIT "")
set(CMAKE_STATIC_LINKER_FLAGS_RELEASE_INIT "")
