#ifndef PH_LOCALIZATION_RESOURCES_H
#define PH_LOCALIZATION_RESOURCES_H

#define PH_LOCALIZATION_STRING_BASE 60000
#define PH_LOCALIZATION_STRING_LIMIT 4096

#define IDS_PH_MAIN_MENU_SYSTEM (PH_LOCALIZATION_STRING_BASE + 0)
#define IDS_PH_MAIN_MENU_VIEW   (PH_LOCALIZATION_STRING_BASE + 1)
#define IDS_PH_MAIN_MENU_TOOLS  (PH_LOCALIZATION_STRING_BASE + 2)
#define IDS_PH_MAIN_MENU_USERS  (PH_LOCALIZATION_STRING_BASE + 3)
#define IDS_PH_MAIN_MENU_HELP   (PH_LOCALIZATION_STRING_BASE + 4)

#endif
